<?php
    foreach($dataAll as $element) {
        echo "<div style='background-color:yellow;margin-left:20px;padding:20px;display:inline-block'>
        <a href=".$this->url('onerubrique', array('id' => $element['menu_id'])).">".$element['titre_fr']."</a></div>";
    }
?>
<div style="border:2px solid black;">
    <!-- Contenu de la rubrique -->
    <?php
        echo $rubrique['content_fr'];
    ?>
</div>