<?php

    echo $this->headLink()->prependStylesheet($this->basePath('js/DataTables-1.10.10/media/css/jquery.dataTables.css'));    
    echo $this->headScript()->prependFile($this->basePath('js/DataTables-1.10.10/media/js/jquery.dataTables.js'));

    //exception suppression rubrique
    echo "<div class='panel_admin'>";
    if($langue == 'fr') {
        if(isset($exception)) {
            echo "<h2>Erreur de suppression. Veuillez réessayer.</h2>";
        }
        else {
            echo "<a id='lien_rubriques' class='btn btn-sm btn-primary'>Gestion des rubriques</a>";
            echo "<a id='lien_publications' class='btn btn-sm btn-primary'>Gestion des publications</a>";
            /*echo "<a href=".$this->url('disconnect', array('action' => 'disconnect', 'langue' => $langue)).">"
                . "<img src=".$this->basePath().'/img/logout.png'." alt='Se déconnecter' width=30 height=30 />Se déconnecter</a>";*/
            echo "<a href=".$this->url('disconnect', array('action' => 'disconnect', 'langue' => $langue))." class='btn btn-sm btn-danger'>Se déconnecter</a>";
        }
    }
    else if($langue == 'en') {
        if(isset($exception)) {
            echo "<h2>Deleting error. Please retry.</h2>";
        }
        else {
            echo "<a id='lien_rubriques' class='btn btn-sm btn-primary'>Rubrics management</a>";
            echo "<a id='lien_publications' class='btn btn-sm btn-primary'>Publications management</a>";
            /*echo "<a href=".$this->url('disconnect', array('action' => 'disconnect', 'langue' => $langue)).">"
                . "<img src=".$this->basePath().'/img/logout.png'." alt='Log out' width=30 height=30 />Log out</a>";*/
            echo "<a href=".$this->url('disconnect', array('action' => 'disconnect', 'langue' => $langue))." class='btn btn-sm btn-danger'>Log out</a>";
        }
    }
    echo "</div>"; //fermeture div admin_btn
    
?>

<!----------------------------------------------- GESTION RUBRIQUES ---------------------------------------------------->

<div id="gestion_rubriques">
    <center>
    <?php 
        if($langue == 'fr') {
                    /*echo "<a href=".$this->url('createrubrique', array('action' => 'createRubrique', 'langue' => $langue))
                           ."><img src=".$this->basePath().'/img/add.png'." alt='Créer une rubrique' width='30' height='30'/>Créer une rubrique</a>";*/
            echo "<a href=".$this->url('createrubrique', array('action' => 'createRubrique', 'langue' => $langue))." class='btn btn-sm btn-success' id='btn_creation_rub'>Créer une rubrique</a>";
        }
        else if($langue =='en') {
                    /*echo "<a href=".$this->url('createrubrique', array('action' => 'createRubrique', 'langue' => $langue))
                           ."><img src=".$this->basePath().'/img/add.png'." alt='Create a rubric' width='30' height='30'/>Create a rubric</a>";*/
            echo "<a href=".$this->url('createrubrique', array('action' => 'createRubrique', 'langue' => $langue))." class='btn btn-sm btn-success' id='btn_creation_rub'>Create a rubric</a>";
        }
    ?>
    </center>
    <div class="container theme-showcase">
        <?php
        if(!isset($exRubriques)) {
        ?>
        <!-- Tableau JS -->
            <table id="table_rubriques" class="display">
                <thead>
                    <tr>
                        <?php 
                        if($langue == 'fr') {
                            echo "<th>Titre français</th>
                                <th>Titre anglais</th>
                                <th>Date de création</th>
                                <th>Date de modification</th>
                                <th>Visible</th>
                                <th>Position</th>
                                <th>Actions</th>";
                        }
                        else if($langue == 'en') {
                            echo "<th>French title</th>
                                <th>English title</th>
                                <th>Creation date</th>
                                <th>Updating date</th>
                                <th>Visible</th>
                                <th>Position</th>
                                <th>Actions</th>";
                        } 
                         ?>
                    </tr>
                </thead>
                <tbody>
                <?php
                    foreach($listeRubrique as $rubrique) {
                        echo "<tr>";
                            //echo "<td>".$rubrique['ID']."</td>";
                        echo "<td>".$rubrique['titre_fr']."</td>";
                            echo "<td>".$rubrique['titre_en']."</td>";
                            echo "<td>".$rubrique['date_creation']."</td>";
                            echo "<td>".$rubrique['date_modification']."</td>";
                            if($rubrique['actif'] == 1) {
                                if($langue == 'fr') {
                                    echo "<td>Oui</td>";
                                }
                                else if($langue =='en') {
                                    echo "<td>Yes</td>";
                                }
                            }
                            else if($rubrique['actif'] == 0) {
                                if($langue == 'fr') {
                                    echo "<td>Non</td>";
                                }
                                else if($langue =='en') {
                                    echo "<td>No</td>";
                                }
                            }
                            echo "<td>".$rubrique['position']."</td>";
                            if($langue == 'fr') {
                                echo "<td><a href=".$this->url('delrubrique', array('action' => 'deleteRubrique', 'id_menu' => $rubrique['menu_id'], 'langue' => $langue)).">"
                                    . "<img src=".$this->basePath().'/img/delete.png'." alt='Supprimer cette rubrique' width=30 height=30 /> "
                                    . "Supprimer</a>";
                                echo "<a href=".$this->url('admrubrique', array('action' => 'modifRubrique', 'id_menu' => $rubrique['menu_id'], 'langue' => $langue)).">"
                                    . "<img src=".$this->basePath().'/img/edit.png'." alt='Editer cette rubrique' width=30 height=30 /> "
                                    . "Editer</a>";
                            }
                            else if($langue =='en') {
                                echo "<td><a href=".$this->url('delrubrique', array('action' => 'deleteRubrique', 'id_menu' => $rubrique['menu_id'], 'langue' => $langue)).">"
                                    . "<img src=".$this->basePath().'/img/delete.png'." alt='Delete this rubric' width=30 height=30 /> "
                                    . "Delete</a>";
                                echo "<a href=".$this->url('admrubrique', array('action' => 'modifRubrique', 'id_menu' => $rubrique['menu_id'], 'langue' => $langue)).">"
                                    . "<img src=".$this->basePath().'/img/edit.png'." alt='Update this rubric' width=30 height=30 /> "
                                    . "Update</a>";
                            }
                            
                            //echo "<td>".$rubrique['menu_id']."</td>";
                        echo "</tr>";
                    }
                ?>
                </tbody>
            </table> 
            <?php 
            } //fermeture !isset($exRubriques)
            else {
                echo "<h2>Pas de rubriques.</h2>";
            }    
            ?>
    </div>
</div>

<!----------------------------------------------- GESTION PUBLICATIONS ---------------------------------------------------->

<div id="gestion_publications">
    <center>
    <?php 
        if($langue == 'fr') {
                    /*echo "<a href=".$this->url('createpublication', array('action' => 'createPublication', 'langue' => $langue))
                           ."><img src=".$this->basePath().'/img/add.png'." alt='Créer une publication via formulaire' width='30' height='30'/>Créer une publication via formulaire</a>";*/
            echo "<a href=".$this->url('createpublication', array('action' => 'createPublication', 'langue' => $langue))." class='btn btn-sm btn-success' id='btn_creation_pub1'>Créer une publication via formulaire</a>";
            echo "<a href=".$this->url('bibtexpublication', array('action' => 'createBibtexPublication', 'langue' => $langue))." class='btn btn-sm btn-success' id='btn_creation_pub2'>Créer une publication via fichier Bibtex</a>";    
        }
        else if($langue =='en') {
                    /*echo "<a href=".$this->url('createpublication', array('action' => 'createRubrique', 'langue' => $langue))
                           ."><img src=".$this->basePath().'/img/add.png'." alt='Create a publication with form' width='30' height='30'/>Create a publication</a>";*/
            echo "<a href=".$this->url('createpublication', array('action' => 'createPublication', 'langue' => $langue))." class='btn btn-sm btn-success' id='btn_creation_pub1'>Create a publication with form</a>";
            echo "<a href=".$this->url('bibtexpublication', array('action' => 'createBibtexPublication', 'langue' => $langue))." class='btn btn-sm btn-success' id='btn_creation_pub2'>Create a publication with Bibtex file</a>";
        }
    ?>
    </center>
    <div class="container theme-showcase">
        <?php
        if(!isset($exPublications)) {
        ?>
        <!-- Tableau JS -->
            <table id="table_publications" class="display">
                <thead>
                    <tr>
                        <?php 
                        if($langue == 'fr') {
                            echo "<th>Titre</th>
                                <th>Auteur(s)</th>
                                <th>Date</th>
                                <th>Reference</th>
                                <th>Publieur</th>
                                <th>Nombre de pages</th>
                                <th>Actions</th>";
                        }
                        else if($langue == 'en') {
                            echo "<th>Title</th>
                                <th>Author(s)</th>
                                <th>Date</th>
                                <th>Reference</th>
                                <th>Publisher</th>
                                <th>Page number</th>
                                <th>Actions</th>";
                        } 
                         ?>
                    </tr>
                </thead>
                <tbody>
                <?php
                    foreach($listePublications as $publication) {
                        echo "<tr>";
                            echo "<td>".$publication['titre']."</td>";
                            echo "<td>".$publication['auteurs']."</td>";
                            echo "<td>".$publication['date']."</td>";
                            echo "<td>".$publication['reference']."</td>";
                            echo "<td>".$publication['publisher']."</td>";
                            echo "<td>".$publication['pages']."</td>";
                            if($langue == 'fr') {
                                echo "<td><a href=".$this->url('delpublication', array('action' => 'deletePublication', 'id_publication' => $publication['ID'], 'langue' => $langue)).">"
                                    . "<img src=".$this->basePath().'/img/delete.png'." alt='Supprimer cette publication' width=30 height=30 /> "
                                    . "Supprimer</a>";
                                echo "<a href=".$this->url('admpublication', array('action' => 'modifPublication', 'id_publication' => $publication['ID'], 'langue' => $langue)).">"
                                    . "<img src=".$this->basePath().'/img/edit.png'." alt='Editer cette publication' width=30 height=30 /> "
                                    . "Editer</a>";
                            }
                            else if($langue =='en') {
                                echo "<td><a href=".$this->url('delpublication', array('action' => 'deletePublication', 'id_publication' => $publication['ID'], 'langue' => $langue)).">"
                                    . "<img src=".$this->basePath().'/img/delete.png'." alt='Delete this publication' width=30 height=30 /> "
                                    . "Delete</a>";
                                echo "<a href=".$this->url('admpublication', array('action' => 'modifPublication', 'id_publication' => $publication['ID'], 'langue' => $langue)).">"
                                    . "<img src=".$this->basePath().'/img/edit.png'." alt='Update this publication' width=30 height=30 /> "
                                    . "Update</a>";
                            }
                        echo "</tr>";
                    }
                ?>
                </tbody>
           </table> 
             <?php 
            } //fermeture !isset($exRubriques)
            else {
                echo "<h2>Pas de publications.</h2>";
            }    
            ?>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function() {
        $('#table_rubriques').DataTable();
        $('#table_publications').DataTable();
        $('#gestion_publications').hide();
        
        $('#lien_rubriques').click(function(){
            $('#gestion_publications').hide();
            $('#gestion_rubriques').show();
        });
        
        $('#lien_publications').click(function(){
            $('#gestion_rubriques').hide();
            $('#gestion_publications').show();
        });
    });
</script>