<?php

    //Importation script CKEditor   
    echo $this->headScript()->prependFile($this->basePath('js/ckeditor/ckeditor.js'));

    //$this->headTitle('Modification Rubrique');
    if(isset($exception)) {
        echo "<h2>Erreur lors du remplissage des champs. Veuillez ressaisir les données.</h2>";
    }
    
    $form->setAttribute('action', $this->url('admrubrique', array('id_menu' => $rubriqueToModif['menu_id'], 'langue' => $langue, 'action' => 'modifRubrique')));
    $form->prepare();
    
    echo $this->form()->openTag($form);
    
    //Récupération des inputs et attribution des valeurs par défaut
    $titreFr = $form->get('titre_fr');
    $titreFr->setValue($rubriqueToModif['titre_fr']);
    $titreEn = $form->get('titre_en');
    $titreEn->setValue($rubriqueToModif['titre_en']);
    
    $actifRadio = $form->get('actifradio');
    $actifRadio->setCheckedValue($rubriqueToModif['actif']);
    $actifRadio->setChecked(true);
    
    $position = $form->get('position');
    $position->setValue($rubriqueToModif['position']);
    $textareaFr = $form->get('content_fr');
    $textareaFr->setValue($rubriqueToModif['content_fr']);
    $textareaEn = $form->get('content_en');
    $textareaEn->setValue($rubriqueToModif['content_en']);
    
    //Création du formulaire
    echo $this->formRow($titreFr)."<br /> <br />";
    echo $this->formRow($titreEn)."<br /> <br />";
    echo $this->formRow($actifRadio)."<br /> <br />";
    echo $this->formRow($position)."<br /> <br />";
    echo $this->formRow($textareaFr)."<br /> <br />";
    echo $this->formRow($textareaEn)."<br /> <br />";
    echo $this->formSubmit($form->get('submit'));
    
    echo $this->form()->closeTag();

?>

<script type="text/javascript">
    
    CKEDITOR.replace('editor_fr');
    CKEDITOR.replace('editor_en');
    
</script>