<?php echo $this->doctype(); ?>
 
<html>
    <head>
        <meta charset="utf-8">
        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>
		
        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() .'/css/style.css')
                        ->prependStylesheet($this->basePath() .'/css/bootstrap.css') 
						->prependStylesheet($this->basePath() .'/css/site.css')
						->prependStylesheet($this->basePath() .'/css/pop-up.css');?>
 
        <!-- Scripts -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                      ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                                      ->prependFile($this->basePath() . '/js/jquery.min.js') ?>
 
    </head>
    <body>
        		<div class="site-content">
			<div class="logo"></div>
			<div class="icons-contener">
					<div class="icon"><?php echo "<a href='".$this->url('laRubrique',array('langue' => 'fr','menu_id' => $this->menu_id))."'>";?><img src="../../img/flag-fr.png" /></a></div>
					<div class="icon"><?php echo "<a href='".$this->url('laRubrique',array('langue' => 'en','menu_id' => $this->menu_id))."'>";?><img src="../../img/flag-en.png" /></a></div>
			</div>
			
				<div class="menu-corner-left"></div>
				<div class="menu-container">	
					<div class="menu-button-list">
						<?php
						/// appelle de service pour affichage des rubrique a partir du controller
						/// verification langue
							
						foreach($this->listeRubrique as $item)
						{			
							if($item['actif']==1){
							if($this->menu_id==$item['menu_id']){echo "<div class='menu-item-selected'>";}
							else{echo "<div class='menu-item'>";}
						
							echo "<a href='".$this->url('laRubrique',array('langue' => $this->langue,'menu_id' => $item['menu_id']))."'>";
							
							if($this->langue=='fr'){echo $item['titre_fr'];}
							else{echo $item['titre_en'];}							
							
							echo " </a></div>						
							
							<div class='menu-separator'></div>";
							}
						}
						
						if($this->menu_id==0){echo "<div class='menu-item-selected'>";}
						else{echo "<div class='menu-item'>";}
						echo "<a href='".$this->url('publications',array('langue' => 'fr'))."'>Publications</a></div>";?>
						
					</div>									
				</div>
				<div class="menu-corner-right"></div>
				
			<div class="text-contener">
				<div class="text-content" style="position: relative; overflow: hidden;">
			
					<?php
						echo $this->content;
					?>
			    </div>
			</div>	
			
			
			<div class="cont">
			<div class="footer-corner-left"></div><div class="footer-middle"></div><div class="footer-corner-right"></div>
			</div>	
		</div>               
        <?php echo $this->inlineScript() ?>
    </body>
</html>