<?php echo $this->doctype();?>
 
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>
		
        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() .'/css/style.css')
                        ->prependStylesheet($this->basePath() .'/css/bootstrap.css') 
						->prependStylesheet($this->basePath() .'/css/site.css')
						->prependStylesheet($this->basePath() .'/css/pop-up.css');?>
 
        <!-- Scripts -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                      ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                                      ->prependFile($this->basePath() . '/js/jquery.min.js') ?>
 
    </head>
    <body>
        <?php 
        
        if(!isset($token)) {
            if($this->langue == 'fr') {
                echo "<a class='btn btn-sm btn-primary' href=".$this->url('login', array('langue' => $this->langue, 'action' => 'login')).">Se connecter</a>";
            }
            else if($this->langue == 'en') {
                echo "<a class='btn btn-sm btn-primary' href=".$this->url('login', array('langue' => $this->langue, 'action' => 'login')).">Log in</a>";
            }
        }
        
        ?> 
        		<div class="site-content">
			<div class="logo"></div>
			<div class="icons-contener">                  
                                        <?php
                                        if($this->menu_id == 'admin') {
                                            echo "<div class='icon'><a href=".$this->url('admin',array('langue' => 'fr'))
                                                    ."><img src='../../img/flag-fr.png'/></a></div>";
                                            echo "<div class='icon'><a href=".$this->url('admin',array('langue' => 'en'))
                                                    ."><img src='../../img/flag-en.png'/></a></div>";  
                                        }
                                        else if($this->menu_id == 'pbm') {
                                            echo "<div class='icon'><a href=".$this->url('publications',array('langue' => 'fr'))
                                                    ."><img src='".$this->basePath()."/img/flag-fr.png'/></a></div>"; 
                                            echo "<div class='icon'><a href=".$this->url('publications',array('langue' => 'en'))
                                                    ."><img src='".$this->basePath()."/img/flag-en.png'/></a></div>";  
                                        }
                                        else if($this->menu_id == 'login') {
                                            echo "<div class='icon'><a href=".$this->url('login',array('langue' => 'fr'))
                                                    ."><img src='".$this->basePath()."/img/flag-fr.png'/></a></div>"; 
                                            echo "<div class='icon'><a href=".$this->url('login',array('langue' => 'en'))
                                                    ."><img src='".$this->basePath()."/img/flag-en.png'/></a></div>";  
                                        }
                                        else if($this->menu_id == 'crrub') {
                                            echo "<div class='icon'><a href=".$this->url('createrubrique',array('langue' => 'fr'))
                                                    ."><img src='".$this->basePath()."/img/flag-fr.png'/></a></div>"; 
                                            echo "<div class='icon'><a href=".$this->url('createrubrique',array('langue' => 'en'))
                                                    ."><img src='".$this->basePath()."/img/flag-en.png'/></a></div>";  
                                        }
                                        else if($this->menu_id == 'modifrub') {
                                            echo "<div class='icon'><a href=".$this->url('admrubrique',array('langue' => 'fr', 'id_menu' => $this->id_menu))
                                                    ."><img src='".$this->basePath()."/img/flag-fr.png'/></a></div>"; 
                                            echo "<div class='icon'><a href=".$this->url('admrubrique',array('langue' => 'en', 'id_menu' => $this->id_menu))
                                                    ."><img src='".$this->basePath()."/img/flag-en.png'/></a></div>";  
                                        }
                                        else if($this->menu_id == 'crpubli') {
                                            echo "<div class='icon'><a href=".$this->url('createpublication',array('langue' => 'fr'))
                                                    ."><img src='".$this->basePath()."/img/flag-fr.png'/></a></div>"; 
                                            echo "<div class='icon'><a href=".$this->url('createpublication',array('langue' => 'en'))
                                                    ."><img src='".$this->basePath()."/img/flag-en.png'/></a></div>";  
                                        }
                                        else if($this->menu_id == 'crbibtex') {
                                            echo "<div class='icon'><a href=".$this->url('bibtexpublication',array('langue' => 'fr'))
                                                    ."><img src='".$this->basePath()."/img/flag-fr.png'/></a></div>"; 
                                            echo "<div class='icon'><a href=".$this->url('bibtexpublication',array('langue' => 'en'))
                                                    ."><img src='".$this->basePath()."/img/flag-en.png'/></a></div>";  
                                        }
                                        else if($this->menu_id == 'modifpubli') {
                                            echo "<div class='icon'><a href=".$this->url('admpublication',array('langue' => 'fr', 'id_publication' => $this->id_publication))
                                                    ."><img src='".$this->basePath()."/img/flag-fr.png'/></a></div>"; 
                                            echo "<div class='icon'><a href=".$this->url('admpublication',array('langue' => 'en', 'id_publication' => $this->id_publication))
                                                    ."><img src='".$this->basePath()."/img/flag-en.png'/></a></div>";  
                                        }
                                        else {
                                            echo "<div class='icon'><a href=".$this->url('laRubrique',array('langue' => 'fr','menu_id' => $this->menu_id))."><img src='".$this->basePath()."/img/flag-fr.png' /></a></div>";
                                            echo "<div class='icon'><a href=".$this->url('laRubrique',array('langue' => 'en','menu_id' => $this->menu_id))."><img src='".$this->basePath()."/img/flag-en.png' /></a></div>";
                                        }
                                        ?>
                            
			</div>
			
				<div class="menu-bar">
				<div class="menu-corner-left"></div>
				<div class="menu-corner-right"></div>
				<div class="menu-container">	
					<div class="menu-button-list">
						<?php
                                                // appelle de service pour affichage des rubrique a partir du controller
						// verification langue
                                                if(!isset($this->exceptionAllR)) {
                                                    foreach($this->listeRubrique as $item)
                                                    {			
                                                            if($item['actif']==1) {
                                                                if($this->menu_id==$item['menu_id']){echo "<div class='menu-item-selected'>";}
                                                                else{echo "<div class='menu-item'>";}

                                                                echo "<a href='".$this->url('laRubrique',array('langue' => $this->langue,'menu_id' => $item['menu_id']))."'>";

                                                                if($this->langue=='fr'){echo $item['titre_fr'];}
                                                                else{echo $item['titre_en'];}							

                                                                echo " </a></div>						

                                                                <div class='menu-separator'></div>";
                                                            }
                                                    }
                                                }
						
						if($this->menu_id=='pbm') {
                                                    echo "<div class='menu-item-selected'>";
                                                }
                                                else {
                                                    echo "<div class='menu-item'>";
                                                }
						echo "<a href='".$this->url('publications',array('langue' => $this->langue))."'>Publications</a></div>";
                                                echo "<div class='menu-separator'></div>";
                                                
                                                //vérification token
                                                if(isset($this->token)) {
                                                    if($this->menu_id=='admin' || $this->menu_id=='crrub' || $this->menu_id=='modifrub' || $this->menu_id=='crpubli'
                                                            || $this->menu_id=='crbibtex' || $this->menu_id=='modifpubli') {
                                                        echo "<div class='menu-item-selected'>";
                                                    }
                                                    else {
                                                        echo "<div class='menu-item'>";
                                                    }
                                                    echo "<a href='".$this->url('admin', array('action' => 'index', 'langue' => $this->langue))."'>Administration</a></div>";
                                                    echo "<div class='menu-separator'></div>";
                                                }
                                                ?>
						
					</div>									
				</div>
			</div>
				
				
			<div class="text-contener">
				<div class="text-content" style="position: relative; overflow: hidden;">
			
					<?php
                                            echo $this->content;
					?>
			    </div>
			</div>	
	
		</div>               
        <?php echo $this->inlineScript() ?>
    </body>
</html>