<?php echo "<table cellspacing='0' cellpadding='0'>
	<tbody>
		<tr>
			<td height='40px' align='left' style='vertical-align:top;'>
				<table class='publication-filter-panel' cellpadding='0' cellspacing='0'>
					<tbody>
						<tr>
							<td width='50%' align='center' style='vertical-align:top;'>
								<div class='ibtn' style='position: relative, overflow: hidden;'>
									<a href=".$this->url('publications', array('langue' => $this->langue, 'trie' => 'categ'))."><img class='float-left' src='".$this->basePath().'/img/icon-sort.png'."'/></a>
									<div class='ibtn-lbl'></div>
								</div>
							</td>
							<td width='50%' align='center' style='vertical-align:top;'>
								<div class='ibtn' style='position: relative, overflow: hidden;'>
									<a href='".$this->url('publications', array('langue' => $this->langue, 'trie' => 'date'))."'><img class='float-left' src='".$this->basePath().'/img/icon-sort-date.png'."'/></a>
									<div class='ibtn-lbl'></div>
								</div>
							</td>
						</tr>
					</tbody>
				</table>
			</td>
		</tr>
		<tr>
			<td align='left' style='vertical-align:top;'>
				<div class='publication-contener' style='position: relative; overflow: hidden;'>
				";
				
				//debut tableau par CATEGORIE
				foreach($listeSup as $menu){
				if($trie=='categ')
				{
					if($langue=='fr'){$affiche=$menu['name_en'];}
					else{$affiche=$menu['name_en'];}
				}
				
				elseif($trie=='date')
				{
					$dateSuiv = explode("-", $menu['date']);
					if(!isset($yearPrec)){
						$yearPrec = $dateSuiv[0];
						$affiche = $yearPrec;
					}
					elseif($dateSuiv[0]<$yearPrec)
					{
						$yearPrec = $dateSuiv[0];
						$affiche = $yearPrec;
					}	
					else
					{
						continue;
					}											
				}
				echo "
					<table cellspacing='0' cellpadding='0' style='width:100%'>
						<tbody>
							<tr>
								<td align='left' style='vertical-align:top;'>
									<div class='publications-section-title'>";
									
									echo $affiche;		
										
									echo "</div>
								</td>
							</tr>
							<td align='left' style='vertical-align:top;'>
								<table class='publication-items' cellspacing='0' cellpadding='0' style='width:100%;'>
									<tbody>";
										
										
										
										//debut tableau des publications
										foreach($listePubli as $item){
										$afficher = false;
										
										if($trie=='date'){
											$datePubli = explode("-", $item['date']);
											if($yearPrec==$datePubli[0]){
												$afficher=true;
												}
										}
										elseif(($trie=='categ')&&($item['categorie_id']==$menu['ID'])){$afficher=true;}
										if($afficher==true){
										
										echo "<tr>
											<td align='left' style='vertical-align: top;'>
												<table class='publications-item' cellpadding='0' cellspacing='0'>
													<tbody>
														<tr>
															<td align='left' style='vertical-align:top;'>
																<div class='gwt-HTML' style='white-space:normal';>
																	<div>";
																									
																		echo "<span class='publi-ref'>[".$item['ID']."] </span>";
																		echo "<span class='publi-authors'>".$item['auteurs'].", </span>";
																		echo "<span class='publi-titre'>".$item['titre'].", </span>";
																		echo "<span class='publi-booktitle'>".$item['journal']."</span>";
																		echo "<span class='publi-volume'>".$item['volume']."</span>";
																		echo "<span class='publi-number'>".$item['number']."</span>";
																		echo "<span class='publi-pages'>".$item['pages']."</span>";
																		echo "<span class='publi-publisher'>".$item['publisher']."</span>";
																		echo "<span class='publi-date'>".$item['date']."</span><br>";
																		?><a class='btn btn-xs btn-info' id='<?php echo $item['ID'] ?>'  onClick="affichage(<?php echo $item['ID'] ?>)">[En voir plus]</a><?php
																		echo "<span id='publi".$item['ID']."'"; ?>  style="display:none" <?php echo "class='publi-abstract'>".$item['abstract']."</span>";
																		echo "<br><span class='publi-keywords'>".$item['keywords']."</span>";
																	
																	echo "</div>
																</div>
															</td>
														</tr>
														<tr>
															<td align='left' style='vertical-align: top;'>
																<table cellpadding='0' cellspacing='0'>
																	<tbody>
																		<tr>";
																			
																			echo "<td align='left' style='vertical-align:top;'><a href='".$this->basePath().$item['pdf']."' <img class='cursor-pointer' src='".$this->basePath().'/img/icon-pdf.png'."'/></a></td>
																			
																			<td align='left' style='vertical-align:top;'><img class='cursor-pointer' src='".$this->basePath().'/img/icon-tex.png'."'/></td>
																		</tr>
																	</tbody>
																</table>
															</td>
														</tr>
													</tbody>
												</table>
											</td>
										</tr>";}}
									
									//fin affichage publication
									echo "</tbody>
								</table>
							</td>									
						</tbody>
					</table>";}
				//fin affichage differentes categories
				echo "</div>
			</td>
		</tr>							
	</tbody>	
</table>";
 ?>
 <script>
 function affichage(elements){
	if(document.getElementById('publi'+elements).style.display =='inline-block' ){
		document.getElementById('publi'+elements).style.display = 'none';
		document.getElementById(elements).innerHTML = '[En voir plus]';
	}else{
		document.getElementById(elements).innerHTML = '[En voir moins]';
		document.getElementById('publi'+elements).style.display = 'inline-block';
	}
}
</script>