<?php
// partie superieur de publication
echo "<table cellspacing='0' cellpadding='0'>
		<tbody>
			<tr>
				<td height='40px' align 'left' style='vertical-align:top;'>
					<tbody>
						<tr>
							<td height='40px' align='left' style='vertical-align:top;'>
								<table class='publication-filter-panel' cellspacing='0'>
									<tbody>
										<tr>
											<td width='50%' align='center' style='vertical-align:top;'>
												<div class='ibtn' style='position: relative, overflow: hidden;'>
													<img class='float-left' src=''/>
													<div class='ibtn-lbl'>Trier par catégorie</div>
												</div>
											</td>
											<td width='50%' align='center' style='vertical-align:top;'>
												<div class='ibtn' style='position: relative, overflow: hidden;'>
													<img class='float-left' src=''/>
													<div class='ibtn-lbl'>Trier par date</div>
												</div>
											</td>
										</tr>
									</tbody>
								</table>
							</td>
						</tr>
						<td align='left' style='vertical-align: top;'>
							<div class='publication-contener' style='position: relative; overflow: hidden;'>
								<table cellspacing='0' cellpadding='0' style='width:100%'>
									<tbody>";
										foreach($listeCateg as $categ){
										echo "<tr>
											<td align='left' style='vertical-align: top;'>
												<div class='publication-section-title'>";
										if($langue=='fr'){$categ['name_fr'];}
										else{echo $categ['name_en'];}
											
										echo 	"</div>
											</td>
										</tr>
										<td align='left' style='vertical-align: top;'>
											<table class='publication-items' cellspacing='0' cellpadding='0' style='width:100%;'>
												<tbody>";
													foreach($listePubli as $item){
														if($item['categorie_id']==$categ['ID']){
																echo "<tr>
																	<td align='left' style='vertical-align: top;'>
																		<table class='publication-item' cellpadding='0' cellspacing='0'>
																			<tbody>
																				<tr>
																					<td align='left' style='vertical-align: top;'>
																						<div class='gwt-HTML' style='white-space: normal';>
																							<div>";
																								foreach($item as $key => $valeur){
																									echo "<span class='publi-".$key.">".$valeur."</span></br>";
																								}
																							echo "</div>
																						</div>
																					</td>
																				</tr>
																				<tr>
																					<td align='left' style='vertical-align: top;'>
																						<table class='publication-item' cellpadding='0' cellspacing='0'>
																							<tbody>
																								<tr>
																									<td class='publi-tableau'>
																";
															}
														}
													}
										
										"
												
							
					</tbody>
				</td>
			</tr>
		</tbody>
	</table>";

 ?>
 
 
 