<?php

    //Importation script CKEditor   
    echo $this->headScript()->prependFile($this->basePath('js/ckeditor/ckeditor.js'));
    
    if(isset($exModifPublication)) {
        echo "<h2>Erreur lors de la modification de la publication. Veuillez réessayer.</h2>";
    }
    
    $form->setAttribute('action', $this->url('admpublication', array('action' => 'modifPublication', 'id_publication' => $publicationToModif['ID'], 'langue' => $langue)));
    $form->prepare();
    
    echo $this->form()->openTag($form);
    
    //Création du formulaire
    $titre = $form->get('titre');
    $titre->setValue($publicationToModif['titre']);
    $reference = $form->get('reference');
    $reference->setValue($publicationToModif['reference']);
    $auteurs = $form->get('auteurs');
    $auteurs->setValue($publicationToModif['auteurs']);
    $date = $form->get('date');
    $date->setValue($publicationToModif['date']);
    $journal = $form->get('journal');
    $journal->setValue($publicationToModif['journal']);
    $abstract = $form->get('abstract');
    $abstract->setValue($publicationToModif['abstract']);
    $volume = $form->get('volume');
    $volume->setValue($publicationToModif['volume']);
    $nb = $form->get('number');
    $nb->setValue($publicationToModif['number']);
    $pages = $form->get('pages');
    $pages->setValue($publicationToModif['pages']);
    $note = $form->get('note');
    $note->setValue($publicationToModif['note']);
    $keywords = $form->get('keywords');
    $keywords->setValue($publicationToModif['keywords']);
    $series = $form->get('series');
    $series->setValue($publicationToModif['series']);
    $localite = $form->get('localite');
    $localite->setValue($publicationToModif['localite']);
    $publisher = $form->get('publisher');
    $publisher->setValue($publicationToModif['publisher']);
    $editor = $form->get('editor');
    $editor->setValue($publicationToModif['editor']);
    $pdf = $form->get('pdf');
    $pdf->setValue($publicationToModif['pdf']);
    $dateDisplay = $form->get('date_display');
    $dateDisplay->setValue($publicationToModif['date_display']);
    $categorie = $form->get('categorie_id');
    $categorie->setValue($publicationToModif['categorie_id']);
    $bouton = $form->get('submit');
    
    if($langue == 'en') {
        $titre->setLabel('Title');
        $reference->setLabel('Reference');
        $auteurs->setLabel('Author(s)');
        $date->setLabel('Date');
        $journal->setLabel('Journal');
        $abstract->setLabel('Abstract');
        $volume->setLabel('Voulme');
        $nb->setLabel('Number');
        $pages->setLabel('Page number');
        $note->setLabel('Note');
        $keywords->setLabel('Keywords');
        $series->setLabel('Series');
        $localite->setLabel('Localite');
        $publisher->setLabel('Publisher');
        $editor->setLabel('Editor');
        $pdf->setLabel('Upload PDF file');
        $dateDisplay->setLabel('Date to display');
        $categorie->setLabel('Category');
        $bouton->setValue('Submit');
    }
    
    echo $this->formRow($titre)."<br /> <br />";
    echo $this->formRow($reference)."<br /> <br />";
    echo $this->formRow($auteurs)."<br /> <br />";
    if($listeCategories != null) {
        $catList = array();
        foreach($listeCategories as $cat) {
            if($langue == 'fr') {
                $catList[$cat['ID']] = $cat['name_fr'];
            }
            else if($langue = 'en') {
                $catList[$cat['ID']] = $cat['name_en'];
            }
        }
        $categorie->setValueOptions($catList);
        echo $this->formRow($categorie)."<br /> <br />";
    }
    echo $this->formRow($date)."<br /> <br />";
    echo $this->formRow($journal)."<br /> <br />";
    echo $this->formRow($abstract)."<br /> <br />";
    echo $this->formRow($volume)."<br /> <br />";
    echo $this->formRow($nb)."<br /> <br />";
    echo $this->formRow($pages)."<br /> <br />";
    echo $this->formRow($note)."<br /> <br />";
    echo $this->formRow($keywords)."<br /> <br />";
    echo $this->formRow($series)."<br /> <br />";
    echo $this->formRow($localite)."<br /> <br />";
    echo $this->formRow($publisher)."<br /> <br />";
    echo $this->formRow($editor)."<br /> <br />";
    echo $this->formRow($pdf)."<br /> <br />";
    echo $this->formRow($dateDisplay)."<br /> <br />";
    echo $this->formSubmit($bouton);    
    echo $this->form()->closeTag();
