
<script type="text/javascript">
    function checkExtension() {
        var input = document.getElementById('upload');
        var bouton = document.getElementById('submitBibtex');
        var file = input.files[0].name;
        var ext = file.split('.').pop();
        if(ext === 'bib') {
            bouton.disabled = true;
        }
        else {
            bouton.disabled = false;
        }
    }
</script>

<?php

    $this->headTitle('Cr√©ation Publication via fichier Bibtex');
    
    if(isset($errorMsgExtension)) {
        if($langue == 'fr') {
            echo "<p class='erreur_form'>L'extension du fichier doit Ítre bib.</p>";
        }
        elseif($langue == 'en') {
            echo "<p class='erreur_form'>The extension file must be bib.</p>";
        }
    }
    
    $form->setAttribute('action', $this->url('bibtexpublication', array('action' => 'createBibtexPublication', 'langue' => $langue)));
    $form->prepare();
    
    echo $this->form()->openTag($form);
    
    //CrÈation du formulaire
    $bibtex = $form->get('bibtex');
    //$bibtex->setAttribute('onclick', 'checkExtension()');
    $bouton = $form->get('submit');
    
    if($langue == 'en') {
        $bibtex->setLabel('Upload Bibtex file');
        $bouton->setValue('Submit');
    }
    
    echo $this->formRow($bibtex)."<br /> <br />";
    echo $this->formSubmit($bouton);    
    
    echo $this->form()->closeTag();
    
?>