<?php

    echo $this->headLink()->prependStylesheet($this->basePath('js/DataTables-1.10.10/media/css/jquery.dataTables.css'));    
    echo $this->headScript()->prependFile($this->basePath('js/DataTables-1.10.10/media/js/jquery.dataTables.js'));
    
?>

<div class="container theme-showcase">
    
    <!-- Tableau JS -->
        <table id="table_id" class="display">
            <thead>
                <tr>
                    <!--<th>Id rubrique</th>-->
                    <th>Titre français</th>
                    <th>Titre anglais</th>
                    <th>Date de création</th>
                    <th>Date de modification</th>
                    <th>Visible</th>
                    <th>Position</th>
                    <th>Actions</th>
                    <!--<th>Id menu</th>-->
                </tr>
            </thead>
            <tbody>
            <?php
                foreach($listeRubrique as $rubrique) {
                    echo "<tr>";
                        //echo "<td>".$rubrique['ID']."</td>";
                    echo "<td>".$rubrique['titre_fr']."</td>";
                        echo "<td>".$rubrique['titre_en']."</td>";
                        echo "<td>".$rubrique['date_creation']."</td>";
                        echo "<td>".$rubrique['date_modification']."</td>";
                        if($rubrique['actif'] == 1) {
                            echo "<td>Oui</td>";
                        }
                        else if($rubrique['actif'] == 0) {
                            echo "<td>Non</td>";
                        }
                        echo "<td>".$rubrique['position']."</td>";
                        echo "<td><a href=".$this->url('delrubrique', array('action' => 'deleteRubrique', 'id_menu' => $rubrique['menu_id'], 'langue' => $langue)).">"
                            . "<img src=".$this->basePath().'/img/delete.png'." alt='Supprimer cette rubrique' width=30 height=30 /> "
                            . "Supprimer</a>";
                        echo "<a href=".$this->url('admrubrique', array('action' => 'modifRubrique', 'id_menu' => $rubrique['menu_id'], 'langue' => $langue)).">"
                            . "<img src=".$this->basePath().'/img/edit.png'." alt='Editer cette rubrique' width=30 height=30 /> "
                            . "Editer</a>";
                        //echo "<td>".$rubrique['menu_id']."</td>";
                    echo "</tr>";
                }
            ?>
            </tbody>
       </table> 
       <a href=<?php echo $this->url('createrubrique', array('action' => 'createRubrique', 'langue' => $langue)) ?>><img src='<?php echo $this->basePath().'/img/add.png'; ?>' alt="Créer une rubrique" width="30" height="30"/>Créer une rubrique</a>
</div>

<script type="text/javascript">
    $(document).ready(function() {
        $('#table_id').DataTable();
    });
</script>