-- phpMyAdmin SQL Dump
-- version 4.1.14
-- http://www.phpmyadmin.net
--
-- Client :  127.0.0.1
-- Généré le :  Mer 25 Novembre 2015 à 09:48
-- Version du serveur :  5.6.17
-- Version de PHP :  5.5.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Base de données :  `webchercheur`
--

-- --------------------------------------------------------

--
-- Structure de la table `publication`
--

CREATE TABLE IF NOT EXISTS `publication` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `reference` text NOT NULL,
  `auteurs` text NOT NULL,
  `titre` text NOT NULL,
  `date` date NOT NULL COMMENT 'Au format YYYY-MM-DD',
  `journal` text,
  `volume` text,
  `number` text,
  `pages` text,
  `note` text,
  `abstract` text,
  `keywords` text,
  `series` text,
  `localite` text,
  `publisher` text,
  `editor` text,
  `pdf` text,
  `date_display` text,
  `categorie_id` int(5) DEFAULT NULL,
  `doi` text CHARACTER SET utf8 COLLATE utf8_unicode_ci,
  `url` text CHARACTER SET utf8 COLLATE utf8_unicode_ci,
  `institution` text CHARACTER SET utf8 COLLATE utf8_unicode_ci,
  `howpublished` text CHARACTER SET utf8 COLLATE utf8_unicode_ci,
  `urldate` text CHARACTER SET utf8 COLLATE utf8_unicode_ci,
  `isbn` text CHARACTER SET utf8 COLLATE utf8_unicode_ci,
  `chapter` text CHARACTER SET utf8 COLLATE utf8_unicode_ci,
  PRIMARY KEY (`ID`),
  KEY `categorie_id` (`categorie_id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=197 ;

--
-- Contenu de la table `publication`
--

INSERT INTO `publication` (`ID`, `reference`, `auteurs`, `titre`, `date`, `journal`, `volume`, `number`, `pages`, `note`, `abstract`, `keywords`, `series`, `localite`, `publisher`, `editor`, `pdf`, `date_display`, `categorie_id`, `doi`, `url`, `institution`, `howpublished`, `urldate`, `isbn`, `chapter`) VALUES
(1, 'SR08a', 'S. Salva and A. Rollet', 'Testabilit', '2008-06-01', 'Revue Ing', '13', '3', '35--58', 'Usually, Web service compositions are tested by assuming\nthat these ones are executed inside an open environment where all\nthe messages exchanged between the services participating to the\ncomposition are observable. Nevertheless, when services are\ndeployed in partially open environments e.g., Clouds, this\nassumption cannot be sustained. This paper proposes a method to\ncheck whether a service composition is conform to its\nspecification according to the ioco test relation, by considering\nthat the internal messages exchanged between the services are\nhidden but that we can invoke each service directly (or an exact\ncopy). Specifications are modelled with Symbolic Transition\nSystems (STS) that we specialize in Web services with some\nannotations and functions. Our approach consists in decomposing an\nexisting test case set according to the operation interleaving\nthat we formalize with a factor denoted the dependency degree.\nThen, while executing the new test case set, we recover fragments\nof traces (observable reactions) that are reassembled. With the\nfinal traces, we are able to check whether the implemented\ncomposition is ioco-conform to its specification. We illustrate\nour approach with an example derived from the application of\nElectronic Health Record externalization for both patients and\npractitioners, currently in development by the Orange Business Service company.', '', 'composition; partially open environment; ioco test relation; conformance testing; trace reconstruction', '', '', 'Hermes, Lavoisier', '', '', '2008', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(2, 'SF04', 'S. Salva and H. Fouchal', 'Testability Analysis for Timed Systems', '2004-05-01', 'International Journal of Computers and Their Applications (IJCTA)', '', '', '', '', '', '', '', '', '', '', '', '', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(3, 'BFPS01', 'S. Bloch and H. Fouchal and E. Petitjean and  S. Salva', 'Some Issues on Testing Real-Time Systems', '2001-12-01', 'International Journal in Computer Information Science (IJCIS)', '2', '4', '', '', '', '', '', '', 'ACIS', '', '', '', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(4, 'RS09', 'A. Rollet and S. Salva', 'Testing robustness of communicating systems using ioco-based approach', '2009-07-05', 'Proceedings of In 1st IEEE Workshop on Performance evaluation of communications in distributed systems and Web based service architectures, in conjunction with IEEE ISCC 2009', '', '1530-1346 ', '67-72', '', '', '', '', 'Sousse, Tunisia', 'IEEE', '', 'useruploads/files/RS09.pdf', 'July 5 - 8, 2009', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(6, 'SR09b', 'S. Salva and I. Rabhi', 'Automatic web service robustness testing from WSDL descriptions', '2009-05-14', '12th European Workshop on Dependable Computing, EWDC 2009', '', '', '', 'Web Services fall under the so-called emerging technologies\ncategory and are getting more and more used for Internet\napplications or business transactions. Since web services are used\nin large and heterogeneous applications, they need to be reliable.\nSo, we propose in this paper, a robustness testing method which\ngenerates and executes test cases automatically from WSDL\ndescriptions. We analyze the web service observability to find the\nrelevant hazards which may be used for testing and those which are\nalways blocked by SOAP processors. We show that few hazards can be\nreally handled. By reducing them, we reduce the test cost too. We\nimprove the robustness issue detection by separating the SOAP\nprocessor behavior to the web service one. With an academic tool,\nwe show that many web services have robustness issues and that our\nmethod is able to detect them.', '', 'robustness testing, web services, test framework', '', 'Toulouse, France ', '', '', 'useruploads/files/SR09b.pdf', 'may 2009', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(7, 'SL09', 'S. Salva and P. Lauren', 'Automatic Ajax application testing', '2009-05-24', 'Fourth International Conference on Internet and Web Applications and Services, ICIW 2009', '', '', '229-234', 'Asynchronous javascript and XML (AJAX) is a recent group of\ntechnologies used to develop dynamic web pages. Ajax applications\nare wisely used nowadays and need to be tested to ensure their\nreliability.  This paper introduces a method and an architecture\nfor automatic AJAX application testing. We use STS automata for\ndescribing the application and for generating test cases. We\nperform an improved random testing using some predefined values\nand also test purpose based testing for verifying specific properties.\nThe testing framework is composed of several testers which control and monitor the test\nexecution to give a test verdict. The Google map search\napplication is used as an example to illustrate the method', '', 'conformance testing, Ajax application, test architecture', '', 'Venice/Mestre, Italy', 'IEEE Computer Society Press', '', 'useruploads/files/SL09.pdf', 'may 2009', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(8, 'SR08', 'S. Salva and A. Rollet', 'Automatic web service testing from WSDL Descriptions', '2008-06-16', '8th International Conference on Innovative Internet Community Systems I2CS 2008', '2011', '', '', '', '', '', 'Lecture Notes in Informatics (LNI)', 'Schoelcher, Martinique', 'Gesellschaft f', '', 'useruploads/files/SR08.pdf', 'June 16-18, 2008,', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(9, 'RS08', 'A. Rollet and S. Salva', 'Two complementary approaches to test robustness of reactive systems (Invited paper)', '2008-05-22', '17th IEEE International Conference on Automation, Quality and Testing, Robotics AQTR 2010', '', '', '47--53', '', '', '', '', 'Cluj-Napoca, Romania', 'IEEE Computer Society Press', '', 'useruploads/files/RS08.pdf', 'May 22-25 2008', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(11, 'SL07', 'S. Salva and P. Lauren', 'Generation of tests for real-time systems with test purposes', '2007-03-29', '15th International Conference on Real-Time and Network Systems RTNS07', '', '', '35-44', '', '', '', '', 'Nancy, France ', '', '', '', 'march, 2007', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(12, 'SL05', 'S. Salva and P. Lauren', 'G', '2005-04-29', 'Colloque Francophone de l ing', '', '', '', '', '', '', '', 'Bordeaux, France', 'lavoisier', '', '', 'abril, 2005', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(13, 'SL04', 'P. Lauren', 'Testing mobile and distributed systems : method and experimentation', '2004-12-01', '8th International Conference on Distribued Systems (OPODIS)', '', '', '', '', '', '', 'LNCS 3544 2005', 'Grenoble, France', 'springer', '', '', 'dec, 2004', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(14, 'SL03a', 'S. Salva and P. Lauren', 'A Testing Tool using the State Characterization Approach for Timed Systems', '2003-09-01', 'WRTES, satellite workshop of FME symposium', '', '', '', '', '', '', '', 'Pisa, Italy', '', '', '', 'sept 2003', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(15, 'SL03b', 'S. Salva and P. Lauren', 'G', '2003-12-01', 'Colloque Francophone de l ing', '', '', '', '', '', '', '', 'Paris, France', 'lavoisier', '', '', 'dec 2003', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(16, 'SF02', 'S. Salva and H. Fouchal', 'Une m', '2002-04-01', 'RENPAR14', '', '', '', '', '', '', '', 'Hamamet, Tunisie', '', '', '', 'abr 2002', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(17, 'S02', 'S. Salva', 'Testing temporal and behavior events on timed systems with timed test purposes', '2002-12-01', '6th International Conference on Distribued Systems (OPODIS)', '', '', '73--84 ', '', '', '', '', 'Reims, France', 'Studia Informatica Universalis', '', '', 'dec 2002', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(18, 'SRF02', 'S. Salva and A. Rollet and H. Fouchal', 'Temporal and Behavior Characterization of States in Timed Systems', '2002-08-01', '23rd ACIS Annual International Conference on Computer and Information Science (ICIS02)', '', '', '', '', '', '', '', 'Seoul, South Korea', '', '', '', 'aug 2002', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(20, 'SF01a', 'S. Salva and H. Fouchal', 'Some Parameters for Timed System Testability', '2001-06-01', 'ACS/IEEE International Conference on Computer System and Applications (AICCS01 )', '', '', '335-', '', '', '', '', 'Beirut, Lebanon', 'IEEE Computer Society', '', '', 'june, 2001', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(21, 'SF01c', 'S. Salva and H. Fouchal', 'Timed Test Execution and TTCN generation', '2001-08-01', '2nd International Conference on Software Engineering applied to Networking and Parallel/Distributed Computing (SNPD02)', '', '', '', '', '', '', '', 'Nagoya, Japon', 'ACIS', '', '', 'aug 2001', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(22, 'SF01d', 'S. Salva and E. Petitjean and H. Fouchal', 'A Simple Approach for Timed System Testing', '2001-08-01', 'Formal Approaches to Testing of Software (FATES01), A Satellite Workshop of CONCUR01', '', '', '', '', '', '', '', 'Aalborg, Denmark', '', '', '', 'aug 2001', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(23, 'S01', 'S. Salva', 'La qualit', '2001-04-01', '3eme Colloque sur la Mod', '', '', '', '', '', '', '', 'Troyes, France', '', '', '', 'abr 2001', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(24, 'FPS00', 'H. Fouchal and E. Petitjean and S. Salva', 'Timed testing using test purposes', '2000-12-01', '7th IEEE International Conference on Real-Time Computing Systems and Applications (RTCSA00)', '', '', '166-171', '', '', '', '', 'Cheju Island, South Korea', 'IEEE Computer Society', '', '', 'dec 2000', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(25, 'SFB00', 'S. Salva and H. Fouchal and S. Bloch', 'Metrics for Timed Systems Testing', '2000-12-01', '4th International Conference on Distribued Systems (OPODIS)', '', '', '', '', '', '', '', 'Paris, France', '', '', '', 'dec 2000', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(26, 'SALV01', 'S. Salva', 'Th', '2001-12-01', '', '', '', '', 'Le co', '', 'conformance testing, timed systems, testability', '', 'reims, france', '', '', 'useruploads/files/SALV01.PDF', 'dec, 2001', 4, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(27, 'SALV0', 'S. Salva', 'seminaire Testabilit', '2000-10-01', '', '', '', '', '', '', '', '', '', '', '', 'useruploads/files/SALV0.pdf', 'oct, 2000', 5, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(28, 'SALV02', 'S. Salva', 'S', '2002-03-01', '', '', '', '', '', '', '', '', '', '', '', 'useruploads/files/SALV02.pdf', 'march, 2002', 5, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(29, 'RR02', 'S. Salva and H. Fouchal', 'Research report: The influence of time in timed systems testing', '2002-01-01', '', '', '', '', '', '', '', '', '', 'LERI-Resycom', '', 'useruploads/files/RR02.pdf', '2002', 3, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(30, 'RR03', 'S. Salva and J. Toussain', 'Research report: Description d?un outil de g', '2003-01-01', '', '', '', '', '', '', '', '', '', '', '', 'useruploads/files/RR03.pdf', '2003', 3, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(31, 'SALV07a', 'S. Salva', 'S', '2007-01-01', '', '', '', '', '', '', '', '', '', '', '', 'useruploads/files/SALV07a.pdf', '2007', 5, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(32, 'SALV07b', 'S. Salva', 'S', '2007-01-01', '', '', '', '', '', '', '', '', '', '', '', 'useruploads/files/SALV07b.pdf', '2007', 5, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(33, 'RR09', 'Salva Sebastien and Issam Rabhi', 'research report: Statefull web service robustness, extended paper', '2009-09-01', '', '', '', '', '', 'http://www.isima.fr/limos/publi/RR-09-09.pdf', '', '', '', '', '', '', '2009', 3, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(39, 'SR10', 'S. Salva and I. rabhi', 'Statefull web service robustness', '2010-05-09', 'The Fifth International Conference on Internet and Web Applications and Services, ICIW10', '', '', '167-173 ', 'Web Services fall under the so-called emerging technologies\ncategory and are getting more and more used for Internet\napplications or business transactions. Since Web Services are\noften the foundation of large applications, they need to be\nreliable and robust. So, we propose in this paper, a robustness\ntesting method of stateful Web Services, modeled with Symbolic\nTransition Systems \\cite{FTW05}. We analyze the Web Service\nobservability and the hazard effectiveness in a SOAP environment\n\\cite{SOAP}. Then, we propose a test case generation method based\non the two hazards "Using unusual values" and "Replacing /Adding\noperation names", which are the only ones that can be applied. The\nAmazon E-commerce Web Service is taken as example', '', 'Robustness testing, stateful Web Services, STS, test architecture', '', 'Barcelona, Spain', 'IEEE Computer Society Press', '', 'useruploads/files/SR10.pdf', 'May 9 - 15, 2010 ', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(40, 'SR10b', 'S. Salva and I. Rabhi', 'A preliminary study on BPEL process testability', '2010-04-01', 'QuomBat2010, ICST Workshop on Quality of Model-Based Testing, Co-located with  ICST  2010, Third International Conference on Software Testing, Verification, and Validation Workshops (ICSTW), 2010 Third International Conference on Software Testing, Verification, and Validation Workshops (ICSTW), 2010', '', '', '62-71', '', '', '', '', 'Paris, France', 'IEEE Computer Society', '', 'useruploads/files/SR10b.pdf', 'April 10, 2010', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(42, 'SLR10', 'Sebastien Salva and Patrice Laurencot and Issam Rabhi', 'An Approach Dedicated for Web Service Security Testing', '2010-08-22', '5th International Conference on Software Engineering Advances, International Conference, ICSEA10', '', '', '494-500', 'Web Services are more and more used in designing and building\nsystems in open and dynamic distributed environments. The security\nof these transactions is becoming a critical issue. This paper\nproposes a security testing method for stateful Web Services. We\ndefine some specific security rules with the Nomad language. Then,\nwe construct test cases from a symbolic specification and test\npurposes derived from the previous rules. We present some\nexperimentation results based on roughly 100 Web Services and we\nshow that 11 percent have vulnerabilities, using the rules introduce in the article.', '', 'Web Services; Security rules; Test purposes; Test generation', '', 'Nice, France', 'IEEE Computer Society', '', 'useruploads/files/SLR10.pdf', 'August 22-27, 2010', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(43, 'CZ10', 'Cavalli, A.  Tien-Dung Cao  Mallouli, W.  Martins, E.  Sadovykh, A.  Salva, S.  Zaidi, F.', 'WebMov: A Dedicated Framework for the Modelling and Testing of Web Services Composition', '2010-07-22', 'ICWS 2010 - 8th IEEE International Conference on Web Services', '', '', '377-384', '', '', '', '', 'Miami, USA', 'IEEE Computer Society', '', '', 'July 2010', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(44, 'SR09', 'S. Salva, A. Rollet', 'Test purpose generation for timed protocol testing', '2009-07-20', 'Proceedings of the 2009 Second International Conference on Communication Theory, Reliability, and Quality of Service, CTRQ 2009', '', '', '8--14', '', '', '', '', 'Colmar, France', 'IEEE Computer Society Press ', '', 'useruploads/files/SR09.pdf', 'July 20-25, 2009 ', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(45, 'SR10d', 'S. Salva and I. Rabhi', 'Robustesse des Services Web persistants', '2010-05-01', 'MOSIM10, 8', '', '', '', '', '', '', '', 'Hammanet, Tunisy', '', '', '', 'may, 2010', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(46, 'S11', 'S. Salva', 'An observability enhancement method of ABPEL specifications', '2011-03-27', 'The 2nd International Conference on    Engineering and Meta-Engineering: ICEME 2011   ', '', '', '1--6', '', '', '', '', 'Orlando, Florida USA', 'IIIS', '', 'useruploads/files/S11.pdf', 'March 27-30, 2011 ', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(47, 'S11b', 'S. Salva', 'Automatic test purpose generation for Web services', '2011-06-20', 'International Conference on Electric and Electronics (EEIC 2011) ', '99', '1876-1100', '721--728', '', '', '', 'Lecture Notes in Electrical Engineering', 'Nanchang University, China ', 'Springer Berlin Heidelberg', 'Wang, Xiaofeng', 'useruploads/files/S11b.pdf', 'june 20-22, 2011', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(49, 'S11c', 'S', 'An Approach For Testing Web Service Compositions When Internal Messages Are Unobservable', '2011-09-01', 'International Journal of Electronic Business Management (IJEBM), Special Issue on New web technologies for collaborative product and process commerce and concurrent engineering', '9', '4', '334-344', 'Usually, Web service compositions are tested by assuming that all the messages ex-changed between the services, participating to the composition, are observable. Nev-ertheless, when services are deployed in an infrastructure which restricts access or when they are deployed on Clouds, this assumption cannot be sustained. Indeed, these environments do not allow extracting the observable reactions of a composition under test (impossibility to install testers or sniffer based tools in the environment). So, this paper proposes a method to check whether a service composition conforms its speci-fication with reference to the ioco test relation, by considering that the internal mes-sages exchanged between the services are hidden but that we can invoke each service one by one (or an exact copy). We propose a method which decomposes an existing test case set according to the operation interleaving that we formalize with a factor denoted the dependency degree. Then, while executing the new test case set, we re-cover fragments of traces (observable reactions) that are reassembled. With the final traces, we are able to check whether the implemented composition is ioco-conform to its specification in the real environment where is deployed the composition.', 'submitted: 2011 january\naccepted: 2011 may\n', 'Web service composition, ioco test relation, conformance testing, trace reconstruction  ', '', '', 'Electronic Business Management Society', '', '', 'nov, 2011', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(52, 'S11d', 'S', 'Passive testing with proxy tester', '2011-10-01', 'International Journal of  Software Engineering and Its Applications (IJSEIA)', '5', '4', '1--16', 'Passive testing is an alternative testing approach whose purpose\nis to passively analyze an implementation behaviour without\ndisturbing it. Usually, passive testing methods extract traces by\nmeans of sniffer-based tools, running in the same environment as\nthe implementation. Nevertheless, many implementation environments\nprevent from setting a sniffer-based tool for security or\ntechnical reasons. We propose a passive testing method based on\nthe notion of proxy-tester which represents an intermediary\nbetween client applications and the implementation. We define a\nproxy-tester as a product between the specification and its\ncanonical tester, which is able to receive the client traffic and\nto forward it to the implementation and vice versa. It also aims\nto analyze the implementation traces to detect faults. We define a\nnon conformance relation between the implementation, its\nspecification and the external environment from which is received\nthe client traffic. We also provide some preliminary results on\nthe Amazon E-commerce Web service and discuss about the\nproxy-tester benefits.\n', 'submitted: 2011 june\naccepted 2011 august\npublished 2011 october', 'passive testing; proxy-tester; STS; conformance relation.', '', '', 'Science & Engineering Research Support soCiety  (SERSC)', '', '', 'october 2011', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(53, 'S12b', 'S', 'Modelling and testing of service compositions in partially open environments', '2012-05-01', 'Studia Unformatica Universalis, special issue on "Mod', '10', '1', '155-185 ', '', 'submitted: 2011 march\naccepted: 2011 september\n', '', '', '', 'HERMANN', '', 'useruploads/files/S12b.pdf', 'may 2012', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(54, 'S12f', 'S. SALVA and A. Rollet', 'A pragmatic approach for testing stateless and stateful Web Service Robustness', '2012-10-01', 'Studia Informatica Universalis', '10', '2', '139-179', 'The interest in testing methodologies dedicated to Web\nServices is soaring as much as the massive use of these\ncomponents. Since Web Services are heterogeneous in nature and\ntake part in complex Business processes, robustness testing which\nis the topic of this paper, is an important step to build them\nwith confidence. Firstly, we focus on the SOAP environment which\nis used to call Web Service operations in an XML format. We show\nthat SOAP must be taken into account in testing methods because it\nsubstantially modifies the Web Service observable behaviour and\nblocks many classical hazards used for testing. Then, we propose\ntwo approaches: the first one aims to test stateless Web Services,\nrepresented by relational models. The second approach is dedicated\nto stateful ones modelled with Symbolic Transition Systems. For\nboth methods, the SOAP environment is taken into account by\nfiltering the messages or by completing the specification. These\nmethods have been experimented with an academic tool on many Web\nServices deployed on the Internet. This experimentation shows that\nseveral ones have robustness issues and that our methods are able\nto detect them.', '', 'Robustness testing; stateless, stateful Web Services; testing framework', '', '', 'Hermann', '', '', '2012', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(55, 'SR11', 'S. SALVA and I. Rabhi', 'A Test Purpose and Test Case Generation Approach for SOAP Web Services', '2011-10-23', 'The Sixth International Conference on Software Engineering Advances  ICSEA 2011', '', '', '35-42', '', '', '', '', 'barcelona, spain', 'XPS (Xpert Publishing Services)', '', 'useruploads/files/SR11.pdf', '2011, October 23-29', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(56, 'SBD07', 'S. Salva and C. Bastoul and C. Delamare', 'Web Service Call Parallelization Using OpenMP', '2007-06-20', '3rd INTERNATIONAL WORKSHOP on OpenMP (IWOMP) 2007', '4935/2008', '', '185-194', '', '', '', 'LNCS', 'Tsinghua University, Beijing, China', 'Springer Verlag', '', '', '2007', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(57, 'S12a', 'S', 'A Guided Web Service Security Testing Method', '2012-04-20', 'Book: Emerging Informatics - Innovative Concepts and Applications, Chapter 11', '', '', '195-222', 'http://www.intechopen.com/books/emerging-informatics-innovative-concepts-and-applications/a-guided-web-service-security-testing-method', '', '', '', '', 'Intech', 'Shah Jahan (Ed.)', '', '2012-04-20', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(59, 'S12c', 'S', 'HDR (Habilitation ', '2012-05-18', 'Universit', '', '', '', '', '', '', '', '', '', '', 'useruploads/files/hdr.pdf', '2012, may', 4, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(61, 'ZSP12', 'Stassia R. Zafimiharisoa and S. Salva and P. Lauren', 'An Automatic Security Testing approach of Android Applications', '2012-11-18', 'The Seventh International Conference on Software Engineering Advances (ICSEA 2012)', '', '', '643-646', '', '', '', '', 'Lisbon, Portugal', 'XPS (Xpert Publishing Services),', '', 'useruploads/files/ZSP12.pdf', '2012 nov.', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(63, 'SR11b', 'S', 'Automatic web service testing from wsdl descriptions. ', '2011-06-01', 'In 11th International Conference on Innovative Internet Community Services (I2CS 2011)', '186', '', '217--226', '(late publication of [SR08])', '', '', '', 'Berlin, Germany', '', 'Lecture Notes in Informatics', '', '2011 june', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(64, 'S12e', 'S', 'Passive Testing of Symbolic Systems. A IOCO Proxy-Tester Based Approach', '2012-07-01', 'International Review on Computers and Software (IRECOS)', '7', '4', '', '', '', '', '', '', '', 'praise worthy prize', '', '2012 july', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(65, 'S12d', 'S', 'An approach for testing passively Web service compositions in Clouds', '2012-07-01', 'SERP''12, The 2012 International Conference on Software Engineering Research and Practice, WorlComp''12', '', '', '', '', '', '', '', '', '', '', '', '2012 july', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(66, 'SC13', ' S', 'Combining Passive Conformance Testing and Runtime Verification: Application to Web Service Compositions Deployed in Clouds', '2013-08-01', 'Software Engineering Research, Management and Applications', '496', '', '99-116', 'This paper proposes a model-based testing approach which combines two monitoring methods, runtime verification and passive testing. Starting from ioSTS (input output Symbolic Transition System) models, this approach generates monitors to check whether an implementation is conforming to its specification and meets safety properties. This paper also tackles the trace extraction problem by reusing the notion of proxy to collect traces from environments whose access rights are restricted. Instead of using a classical proxy to collect traces, we propose to generate a formal model from the specification, called Proxy-monitor, which acts as a proxy and which can directly detect implementation errors. We apply and specialise this approach on Web service compositions deployed in PaaS environments.', '(selected publication of ', '          Passive Testing         Runtime Verification         Proxy         ioco         Web services         Clouds', 'Studies in Computational Intelligence', '', 'Lee, Roger', 'Springer International Publishing', 'useruploads/files/SC13.pdf', '2013 july', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(67, 'SZ13', 'S', 'Data vulnerability detection by security testing for Android applications', '2013-08-01', '2013 Information Security for South Africa, Johannesburg,                South Africa (ISSA), August 14-16', '', '', '1-8', '', '?The Android intent messaging is a mechanism that ties components together to build Mobile applications. Intents are kinds of messages composed of actions and data, sent by a component to another component to perform sev- eral operations, e.g., launching a user interface. The intent mechanism eases the writing of Mobile applications, but it might also be used as an entry point for security attacks. The latter can be easily sent with intents to components, that can indirectly forward attacks to other components and so on. In this context, this paper proposes a Model-based security testing approach to attempt to detect data vulnerabilities in Android applications. In other words, this approach generates test cases to check whether components are vulnerable to attacks, sent through intents, that expose personal data. Our method takes Android applications and intent-based vulnerabilities formally expressed with models called vulnerability patterns. Then, and this is the originality of our approach, partial speci?cations are automatically generated from con?guration ?les and component codes. Test cases are then automatically generated from vulnerability patterns and the previous speci?- cations. A tool, called APSET, is presented and evaluated with experimentations on some Android applications. ', 'Security testing, Android applications, Model- based testing, Mobile device security', '', 'Johannesburg, South Africa', '', '', 'useruploads/files/SZ13.pdf', 'aug 2013', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(68, 'SZL13', 'S', 'Intent Security Testing - An Approach to Testing the Intent-based                Vulnerability of Android Components', '2013-07-01', 'SECRYPT 2013 - Proceedings of the 10th International Conference on Security and Cryptography', '', '', '355-362', '', 'The intent mechanism is a powerful feature of the Android platform that helps compose existing components together to build a Mobile application. However, hackers can leverage the intent messaging to extract personal data or to call components without credentials by sending malicious intents to components. This paper tackles this issue by proposing a security testing method which aims at detecting whether the components of an Android application are vulnerable to malicious intents. Our method takes Android projects and intent-based vulnerabilities formally represented with models called vulnerability patterns. The originality of our approach resides in the generation of partial specifications from configuration files and component codes to generate test cases. A tool, called APSET, is presented and evaluated with experimentations on some Android applications.', ' Security Testing; Android Applications; Model-Based Testing ', '', 'Reykjav', ' SciTePress 2013 ISBN 978-989-8565-73-0', '', 'useruploads/files/SZL13.pdf', 'july 2013', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(69, 'SP14', 'S', 'Conformance Testing with ioco Proxy-Testers: Application to Web service compositions deployed in Clouds', '2014-01-01', 'International Journal of Computer Aided Engineering and Technology (IJCAET)', '', '', '', ' This paper describes a conformance testing method which aims\n at passively testing the conformance of component-based systems. The paper\n addresses the problem of reaction sequence observation in implementation\n environments where the installation of testing tools is not possible. The\n originality of the method resides in the definition of a Proxy-tester model from a\n specification and in the reformulation of the\n ioco\n test relation with Proxy-tester\n properties. Initially, we define the Proxy-tester model and we give the theoretical\n background to automatically generate Proxy-testers from specifications modelled\n with IOSTSs (input output Symbolic Transition System). The second part of\n the paper describes the application of this method on Web service compositions\n deployed in Clouds. We provide algorithms and passive tester architectures to\n collect traces from several concurrent composition instances running in parallel.\n Finally, we present the testing tool Cloud Paste and experiment results on two\n Clouds, Google AppEngine and Windows Azure', '', 'Passive testing; Proxy; Ioco; Google AppEngine; Windows Azure ', '', '', 'Inderscience', '', 'useruploads/files/SP14.pdf', '2014', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(70, 'SZ14', 'S', 'APSET, an Android aPplication SEcurity Testing tool for detecting intent-based vulnerabilities', '2014-01-02', 'International Journal on Software Tools for Technology Transfer (STTT)', '', '', '1-21', '', 'The Android messaging system, called in-\n tent, is a mechanism that ties comp onents together to\n build applications for smartphones. Intents are kinds of\n messages comp osed of actions and data, sent by a com-\n p onent to another comp onent to p erform several op era-\n tions, e.g., launching a user interface. The intent mech-\n anism o?er a lot of exibility for developing Android\n applications, but it might also b e used as an entry p oint\n for security attacks. The latter can b e easily sent with\n intents to comp onents, that can indirectly forward at-\n tacks to other comp onents and so on. In this context, this\n pap er prop oses APSET, a to ol for Android aPplication\n SEcurity Testing, which aims at detecting intent-based\n vulnerabilities. It takes as inputs Android applications\n and intent-based vulnerabilities formally expressed with\n mo dels called vulnerability patterns. Then, and this is\n the originality of our approach, class diagrams and par-\n tial sp eci cations are automatically generated from ap-\n plications with algorithms re ecting some knowledge of\n the Android do cumentation. These partial sp eci cations\n avoid false p ositives and re ne the test result with sp e-\n cial verdicts notifying that a comp onent is not compli-\n ant to its sp eci cation. Furthermore, we prop ose a test\n case execution framework which supp orts the receipt\n of any exception, the detection of application crashes,\n and provides a nal XML test rep ort detailing the test\n case verdicts. The vulnerability detection effectiveness of\n APSET is evaluated with exp erimentations on randomly\n chosen Android applications of the Android Market', ' Android Application Development; Model-Based Testing; Security Testing ', '', '', 'Springer Berlin Heidelberg', '', 'useruploads/files/SZ14.pdf', '2014', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(71, 'SZ13b', 'S. Salva and Stassia R. Zafimiharisoa', 'Detection of intent-based vulnerabilities in Android applications, chapter 24', '2013-12-01', 'Book ICT: Emerging Trends in Information and Communication Technologies Security', '', '24', '', '', '', ' Security; Android Application Development; intent mechanism', '', '', 'Elsevier', '', 'useruploads/files/ICT143.zip', '2013', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(72, 'DS14', 'William Durand and S', 'Inference de modeles dirigee par la logique metier', '2014-06-11', 'AFADL (Approches Formelles dans l''Assistance au D', '', '', '', '', '', ' IOSTS; test automatique; inf', '', 'paris, France', '', '', 'useruploads/files/DS14.pdf', 'juin 2014', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(73, 'S14', 'S', 'S', '2014-04-02', '', '', '', '', '', '', '', '', '', '', '', 'useruploads/files/semmontp.zip', 'avril 2014', 5, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(74, 'SZ14b', 'S', 'Model reverse-engineering of Mobile applications with exploration strategies', '2014-10-12', 'The Ninth International Conference on Software Engineering Advances, ICSEA 2014', '', '', '396-403', 'Best Paper Award', 'This paper presents a model reverse-engineering approach for mobile applications that belong to the GUI application category. This approach covers the interfaces of an application with automatic testing to incrementally infer a formal model expressing the navigational paths and states of the application. We propose the definition of a specialised GUI application model which stores the discovered interfaces and helps limit the application exploration. Then, we present an algorithm based upon the Ant Colony Optimisation technique which offers the possibility to parallelise the exploration and to conceive any application exploration strategy. Finally, our approach is experimented on Android applications and compared to other tools available in the literature.', ' model generation; Automatic testing;  Android application', '', 'Nice, France', '', '', 'useruploads/files/SZ14b.pdf', '2014, october', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(75, 'SC14', 'S', 'Proxy-Monitor: An integration of runtime verification with passive conformance testing.', '2014-09-01', 'International Journal of Software Innovation (IJSI)', '2', '3', '20--42', 'extension of Sera''13', 'This paper proposes a conformance testing method combining two well-known testing approaches, runtime verification and passive testing. Runtime verification addresses the monitoring of a system under test to check whether formal properties hold, while passive testing aims at checking the conformance of the system in the long-term. The method, proposed in this paper, checks whether an implementation conforms to its specification with reference to the ioco test relation. While passively checking if ioco holds, it also checks whether the implementation meets safety properties, which informally state that ?nothing bad ever happens?. This paper also tackles the trace extraction problem, which is common to both runtime verification and passive testing. We define the notion of Proxy-monitors for collecting traces even when the implementation environment access rights are restricted. Then, we apply and specialise this approach on Web service compositions. A Web service composition deployed in different Clouds is experimented to assess the feasibility of the method.', 'Conformance testing, Passive Testing, Runtime Verification, Proxy-Tester, ioco, Monitoring, Service Composition, Clouds. ', '', '', 'IGI Global', '', 'useruploads/files/SC14.pdf', '2014', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(76, 'SD14', 'S', 'Domain-Driven Model Inference Applied To Web Applications.', '2014-07-21', 'The 2014 International Conference on Software Engineering Research and Practice (SERP14)', '', '', '', 'Model inference methods are attracting increased attention from industrials and researchers since they can be used to generate models for software comprehension, for test case generation, or for helping devise a complete model (or documentation). In this context, this paper presents an original inference model approach which recovers models from Web application HTTP traces. This approach combines formal model inference with domain-driven expert systems. Our framework, whose purpose is to simulate this human behaviour, is composed of inference rules, translating the domain expert knowledge, organised into layers. Each yields partial IOSTSs (Input Output Symbolic Transition System), which become more and more abstract and intelligible.', '', '?Model inference, formal model, IOSTS, rule- based system', '', 'Las Vegas, USA', '', '', 'useruploads/files/SD14.pdf', '2014 july, ', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(77, 'DS14b', 'William Durand and S', 'Inferring models with rule-based expert systems ', '2014-12-04', '5th symposium on Information and Communication Technology (SoICT 2014)', '', '', '', '', 'Many works related to software engineering rely upon for- mal models, e.g., to perform model-checking or automatic test case generation. Nonetheless, producing such mod- els is usually tedious and error-prone. Model inference is a research field helping in producing models by generating partial models from documentation or execution traces (ob- served action sequences). This paper presents a new model generation method combining model inference and expert systems. It appears that an engineer is able to recognise the functional behaviours of an application from its traces by applying deduction rules. We propose a framework, applied to Web applications, simulating this reasoning mechanism, with inference rules organised into layers. Each yields par- tial IOSTSs (Input Output Symbolic Transition Systems), which become more and more abstract and understandable.', 'Model inference, automatic testing, IOSTS, expert system', '', 'Hanoi, Vietnam', 'ACM', '', 'useruploads/files/DS14b.pdf', '2014, dec', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(79, 'AZERTY007', 'F. RibÃ©ry', 'Test', '2015-11-24', NULL, NULL, NULL, NULL, NULL, 'nul', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(80, 'dedeedde', 'deededde', 'Testouille', '2015-11-13', NULL, 'tg', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(83, 'frrfrfrfrf', 'tttt', 'gg', '2015-11-26', NULL, NULL, NULL, NULL, NULL, 't(t(', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 3, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(84, 'frf', 'M. Tuloup and J-K. Rowling', 'Okay', '2015-11-13', 'okkkkkkkkkkkkkkk', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 3, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(101, 'frrf', 'M. Tuloup and J-K. Rowling', 'zok', '2015-11-10', 'dddd', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'useruploads/files/IUT-Info_FID_Session_2_Conception_d_un_entrepot_decisionnel_Modelisation.pdf', NULL, 3, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(103, 'regt', 'hy', 'Zyx', '2015-11-03', 'pmo', 'pmo', NULL, NULL, NULL, 'mpo', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(104, 'ddddddd', 'dddddddd', 'Zpmlo', '2015-11-24', 'ddddddd', NULL, NULL, NULL, NULL, 'ddddddddd', NULL, NULL, NULL, NULL, NULL, 'useruploads/files/IUT-Info_FID_Session_2_Conception_d_un_entrepot_decisionnel_Modelisation.pdf', NULL, 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(105, 'fffff', 'fffff', 'Test', '2015-11-04', 'fff', NULL, NULL, NULL, NULL, 'ff', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(107, '87EE8', 'C. Make', 'TestChgt', '2015-11-03', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'useruploads/files/Cours1PDF.pdf', NULL, 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(110, 'Sh:1072', 'Shelah, Saharon', '{}', '2015-01-01', '', '', '', '', '', '', '', '', '', '', '', NULL, '2015-11-21', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(111, 'Sh:1072', 'Shelah, Saharon', '{Test fichier bib}', '2015-01-01', '', '', '', '', '', '', '', '', '', '', '', NULL, '2015-11-21', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(112, 'Sh:1072', 'Shelah, Saharon', '{Test fichier bib}', '2015-01-01', '', '', '', '', '', '', '', '', '', '', '', NULL, '2015-11-22', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(113, 'Sh:1072', 'Shelah, Saharon', '{Test fichier bib}', '2015-01-01', '', '', '', '', '', '', '', '', '', '', '', NULL, '2015-11-22', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(114, 'Sh:1072', 'Shelah, Saharon', '{Test fichier bib}', '2015-01-01', '', '', '', '', '', '', '', '', '', '', '', NULL, '2015-11-22', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(115, 'Sh:1072', 'Shelah, Saharon', '{Test fichier bib}', '2015-01-01', '', '', '', '', '', '', '', '', '', '', '', NULL, '2015-11-22', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(116, 'Sh:1072', 'Shelah, Saharon', '{Test fichier bib}', '2015-01-01', '', '', '', '', '', '', '', '', '', '', '', NULL, '2015-11-22', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(117, 'Sh:1072', 'Shelah, Saharon', '{Test fichier bib}', '2015-01-01', '', '', '', '', '', '', '', '', '', '', '', NULL, '2015-11-22', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(118, 'AZERTY007', 'M. Tuloup and J-K. Rowling', 'zerteez', '2015-11-03', 'okkkkkkkkkkkkkkk', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'useruploads/files/AffichageResultats.pdf', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(119, 'gtg', 'gyhu', 'gthy''', '2015-11-21', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(120, 't(t(''t(t(''', 't(''t(''t''t''', 'e"''rt''(', '2015-11-17', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'frerfe', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(121, 'AZERTY007', 'M. Tuloup and J-K. Rowling', 'Test', '2015-11-12', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(122, 'AZERTY007', 'M. Tuloup and J-K. Rowling', 'Nowwww', '2015-11-18', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(123, 'aaa', 'F. RibÃ©ry', 'Test', '2015-11-03', 'fff', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'useruploads/files/AffichageResultats.pdf', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(124, 'teet', 'ttete', 'ert', '2015-11-25', 'rg', 'grgrgr', 'grgrgr', NULL, NULL, 'grgrgr', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(125, 'aaa', 'trtrgtgtvgb', 'gg', '2015-11-14', 'okkkkkkkkkkkkkkk', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 3, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(126, 'MiSh:1069', 'Malliaris, Maryanthe and Shelah, Saharon', '{Open problems on ultrafilters and some connections to the\n continuum}', '2015-01-01', 'preprint', '', '', '', '', '', '', '', '', '', '', NULL, '2015-11-24', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(127, 'MiSh:1070', 'Malliaris, Maryanthe and Shelah, Saharon', '{Open problems on ultrafilters and some connections to the\n continuum}', '2015-01-01', 'preprint', '', '', '', '', '', '', '', '', '', '', NULL, '2015-11-24', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(128, 'Azim13', 'Azim, Tanzirul and Neamtiu, Iulian', 'Targeted and Depth-first Exploration for Systematic Testing of Android Apps', '2013-01-01', 'Proceedings of the 2013 ACM SIGPLAN International Conference on Object Oriented Programming Systems Languages \\&\\#38; Applications', '', '', '641--660', '', '', 'code coverage, dynamic analysis, google android, greybox testing, gui testing, systematic exploration, taint analysis, test case generation', 'OOPSLA ''13', 'New York, NY, USA', 'ACM', '', NULL, '2015-11-24', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(129, 'Azim13', 'Azim, Tanzirul and Neamtiu, Iulian', 'Targeted and Depth-first Exploration for Systematic Testing of Android Apps', '2013-01-01', 'Proceedings of the 2013 ACM SIGPLAN International Conference on Object Oriented Programming Systems Languages \\&\\#38; Applications', '', '', '641--660', '', '', 'code coverage, dynamic analysis, google android, greybox testing, gui testing, systematic exploration, taint analysis, test case generation', 'OOPSLA ''13', 'New York, NY, USA', 'ACM', '', NULL, '2015-11-24', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(130, 'Angluin:1987', 'Angluin, Dana', 'Learning Regular Sets from Queries and Counterexamples', '1987-01-01', 'Inf. Comput.', '75', '2', '87--106', '', '', '', '', 'Duluth, MN, USA', 'Academic Press, Inc.', '', NULL, '2015-11-24', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(131, '4656395', 'Amalfitano, D. and Fasolino, A.R. and Tramontana, P.', 'Reverse Engineering Finite State Machines from Rich Internet Applications', '2008-01-01', 'Reverse Engineering, 2008. WCRE ''08. 15th Working Conference on', '', '', '69-73', '', '', 'Internet;finite state machines;pattern clustering;reverse engineering;Web application lifecycle;clustering techniques;finite state machines;reverse engineering;rich Internet applications;state explosion;Application software;Automata;Explosions;Information retrieval;Internet;Java;Reverse engineering;Search engines;US Department of Transportation;Usability;Ajax;FSM;RIA;Reverse Engineering', '', '', '', '', NULL, '2015-11-24', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(132, '4656395', 'Amalfitano, D. and Fasolino, A.R. and Tramontana, P.', 'Reverse Engineering Finite State Machines from Rich Internet Applications', '2008-01-01', 'Reverse Engineering, 2008. WCRE ''08. 15th Working Conference on', '', '', '69-73', '', '', 'Internet;finite state machines;pattern clustering;reverse engineering;Web application lifecycle;clustering techniques;finite state machines;reverse engineering;rich Internet applications;state explosion;Application software;Automata;Explosions;Information retrieval;Internet;Java;Reverse engineering;Search engines;US Department of Transportation;Usability;Ajax;FSM;RIA;Reverse Engineering', '', '', '', '', NULL, '2015-11-24', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(133, 'hungar2002', 'Hungar, Hardi and Margaria, Tiziana and Steffen, Bernhard', 'Model Generation for Legacy Systems', '2004-01-01', 'Radical Innovations of Software and Systems Engineering in the Future', '2941', '', '167-183', '', '', '', 'Lecture Notes in Computer Science', '', 'Springer Berlin Heidelberg', 'Wirsing, Martin and Knapp, Alexander and Balsamo, Simonetta', NULL, '2015-11-24', 5, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(134, 'mobiguitar', 'Domenico Amalfitano and Anna Rita Fasolino and Porfirio Tramontana and Bryan Ta and Atif Memon', 'MobiGUITAR -- A Tool for Automated Model-Based Testing of Mobile Apps', '2014-01-01', 'IEEE Software', '99', 'PrePrints', '1', '', '', '', '', 'Los Alamitos, CA, USA', 'IEEE Computer Society', '', NULL, '2015-11-24', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(135, 'guitar', 'Nguyen, BaoN. and Robbins, Bryan and Banerjee, Ishan and Memon, Atif', 'GUITAR: an innovative tool for automated testing of GUI-driven software', '2014-01-01', 'Automated Software Engineering', '21', '1', '65-105', '', '', 'GUI testing; Test automation; Test generation', '', '', 'Springer US', '', NULL, '2015-11-24', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(136, 'dynodroid', 'Machiry, Aravind and Tahiliani, Rohan and Naik, Mayur', 'Dynodroid: An Input Generation System for Android Apps', '2013-01-01', 'Proceedings of the 2013 9th Joint Meeting on Foundations of Software Engineering', '', '', '224--234', '', '', 'Android, GUI testing, testing event-driven programs', 'ESEC/FSE 2013', 'New York, NY, USA', 'ACM', '', NULL, '2015-11-24', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(137, 'SZ14b', 'Sebastien Salva and Stassia R. Zafimiharisoa', 'Model reverse-engineering of Mobile applications with exploration strategies', '2014-10-01', 'The Ninth International Conference on Software Engineering Advances, ICSEA 2014', '', '', '', 'This paper presents a model reverse-engineering approach for mobile applications that belong to the GUI application category. This approach covers the interfaces of an application with automatic testing to incrementally infer a formal model expressing the navigational paths and states of the application. We propose the definition of a specialised GUI application model which stores the discovered interfaces and helps limit the application exploration. Then, we present an algorithm based upon the Ant Colony Optimisation technique which offers the possibility to parallelise the exploration and to conceive any application exploration strategy. Finally, our approach is experimented on Android applications and compared to other tools available in the literature.', 'Best Paper Award', ' model generation; Automatic testing; Android application', '', 'Nice, France', '', '', NULL, '2015-11-24', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `publication` (`ID`, `reference`, `auteurs`, `titre`, `date`, `journal`, `volume`, `number`, `pages`, `note`, `abstract`, `keywords`, `series`, `localite`, `publisher`, `editor`, `pdf`, `date_display`, `categorie_id`, `doi`, `url`, `institution`, `howpublished`, `urldate`, `isbn`, `chapter`) VALUES
(138, 'Choi2013', 'Choi, Wontae and Necula, George and Sen, Koushik', 'Guided GUI Testing of Android Apps with Minimal Restart and Approximate Learning', '2013-01-01', 'SIGPLAN Not.', '48', '10', '623--640', '', '', 'android, automata, gui testing, learning', '', 'New York, NY, USA', 'ACM', '', NULL, '2015-11-24', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(139, 'Choi:2013:GGT:2509136.2509552', 'Choi, Wontae and Necula, George and Sen, Koushik', 'Guided GUI Testing of Android Apps with Minimal Restart and Approximate Learning', '2013-01-01', 'Proceedings of the 2013 ACM SIGPLAN International Conference on Object Oriented Programming Systems Languages \\&\\#38; Applications', '', '', '623--640', '', '', 'android, automata, gui testing, learning', 'OOPSLA ''13', 'New York, NY, USA', 'ACM', '', NULL, '2015-11-24', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(140, 'Broy2005', 'Broy, Manfred and Jonsson, Bengt and Katoen, Joost-Pieter and Leucker, Martin and Pretschner, Alexander', 'Model-Based Testing of Reactive Systems: Advanced Lectures (Lecture Notes in Computer Science)', '2005-01-01', '', '', '', '', '', '', '', '', 'Secaucus, NJ, USA', 'Springer-Verlag New York, Inc.', '', NULL, '2015-11-24', 5, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(141, 'RR14b', 'Salva, Sebastien and Zafimiharisoa, Stassia R. and Lauren\\c{c}ot, Patrice', 'Model generation and automatic testing of GUI applications', '2014-01-01', '', '', '', '', '', '', '', '', '', '', '', NULL, '2015-11-24', 3, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(142, 'monkey', 'Google', 'UI/Application Exerciser Monkey', '2015-01-01', '', '', '', '', 'http://developer.android.com/tools/help/monkey.html, last accessed jan 2014', '', '', '', '', '', '', NULL, '2015-11-24', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(143, 'AD', 'AD', 'Android Developer page', '2001-01-01', 'http:// developer.android.com/index.html, last accessed feb 2013', '', '', '', '', '', '', '', '', '', '', NULL, '2015-11-24', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(144, 'jeron2009167', 'Thierry J\\''eron', 'Symbolic Model-based Test Selection ', '2009-01-01', 'Electronic Notes in Theoretical Computer Science ', '240', '0', '167 - 184', '', '', 'Model-based testing', '', '', '', '', NULL, '2015-11-24', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(145, 'concolicandroid12', 'Anand, Saswat and Naik, Mayur and Harrold, Mary Jean and Yang, Hongseok', 'Automated concolic testing of smartphone apps', '2012-01-01', 'Proceedings of the ACM SIGSOFT 20th International Symposium on the Foundations of Software Engineering', '', '', '1--11', '', '', 'Android, GUI testing, testing event-driven programs', 'FSE ''12', 'New York, NY, USA', 'ACM', '', NULL, '2015-11-24', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(146, 'Joorabchi:2012:REI:2420240.2420457', 'Joorabchi, Mona Erfani and Mesbah, Ali', 'Reverse Engineering iOS Mobile Applications', '2012-01-01', 'Proceedings of the 2012 19th Working Conference on Reverse Engineering', '', '', '177--186', '', '', 'reverse engineering, mobile applications, iOS, model generation', 'WCRE ''12', 'Washington, DC, USA', 'IEEE Computer Society', '', NULL, '2015-11-24', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(147, 'webmate12', 'Dallmeier, Valentin and Burger, Martin and Orth, Tobias and Zeller, Andreas', 'WebMate: a tool for testing web 2.0 applications', '2012-01-01', 'Proceedings of the Workshop on JavaScript Tools', '', '', '11--15', '', '', 'JavaScript, test generation, web applications', 'JSTools ''12', 'New York, NY, USA', 'ACM', '', NULL, '2015-11-24', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(148, 'Amalfitano2012', 'Amalfitano, Domenico and Fasolino, Anna Rita and Tramontana, Porfirio and De Carmine, Salvatore and Memon, Atif M.', 'Using GUI ripping for automated testing of Android applications', '2012-01-01', 'Proceedings of the 27th IEEE/ACM International Conference on Automated Software Engineering', '', '', '258--261', '', '', 'Android, Testing Automation, Testing Tools', 'ASE 2012', 'New York, NY, USA', 'ACM', '', NULL, '2015-11-24', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(149, 'crawljax:tweb12', 'Mesbah, Ali and van Deursen, Arie and Lenselink, Stefan', 'Crawling {Ajax}-based Web Applications through Dynamic Analysis of User Interface State Changes', '2012-01-01', 'ACM Transactions on the Web (TWEB)', '6', '1', '1--30', '', '', '', '', '', '', '', NULL, '2015-11-24', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(150, '5954416', 'Amalfitano, D. and Fasolino, A.R. and Tramontana, P.', 'A GUI Crawling-Based Technique for Android Mobile Application Testing', '2011-01-01', 'Software Testing, Verification and Validation Workshops (ICSTW), 2011 IEEE Fourth International Conference on', '', '', '252-261', '', '', 'graphical user interfaces;mobile computing;program testing;Android mobile application testing;GUI crawling-based technique;Google Android platform;automatic testing;cost effective testing techniques;development tools;rapid crash testing;regression testing;Androids;Crawlers;Graphical user interfaces;Humanoid robots;Mobile communication;Smart phones;Testing;Android Testing Automation;Crash Testing;GUI Crawling;Regression Testing', '', '', '', '', NULL, '2015-11-24', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(151, 'WPX13', 'Yang, Wei and Prasad, Mukul R. and Xie, Tao', 'A grey-box approach for automated GUI-model generation of mobile applications', '2013-01-01', 'Proceedings of the 16th international conference on Fundamental Approaches to Software Engineering', '', '', '250--265', '', '', '', 'FASE''13', 'Berlin, Heidelberg', 'Springer-Verlag', '', NULL, '2015-11-24', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(152, 'Kervinen06model-basedtesting', 'Kervinen, Antti and Maunumaa, Mika and P\\"{a}\\"{a}kk\\"{o}nen, Tuula and Katara, Mika', 'Model-Based testing through a GUI', '2006-01-01', 'Proceedings of the 5th international conference on Formal Approaches to Software Testing', '', '', '16--31', '', '', '', 'FATES''05', 'Berlin, Heidelberg', 'Springer-Verlag', '', NULL, '2015-11-24', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(153, 'Memon:2003:GRR:950792.951350', 'Memon, Atif and Banerjee, Ishan and Nagarajan, Adithya', 'GUI Ripping: Reverse Engineering of Graphical User Interfaces for Testing', '2003-01-01', 'Proceedings of the 10th Working Conference on Reverse Engineering', '', '', '260--', '', '', '', 'WCRE ''03', 'Washington, DC, USA', 'IEEE Computer Society', '', NULL, '2015-11-24', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(154, '5416728', 'Artzi, S. and Kiezun, A. and Dolby, J. and Tip, F. and Dig, D. and Paradkar, A. and Ernst, M.D.', 'Finding Bugs in Web Applications Using Dynamic Test Generation and Explicit-State Model Checking', '2010-01-01', 'Software Engineering, IEEE Transactions on', '36', '4', '474-494', '', '', 'program debugging;program testing;program verification;software tools;Apollo tool;HTML specification;Internet;PHP Web applications;PHP programming language;Web pages;Web script;bugs;dynamic test generation;explicit state model checking;PHP;Software testing;Web applications;dynamic analysis;reliability;verification.', '', '', '', '', NULL, '2015-11-24', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(155, 'Fernandez89animplementation', 'Jean-Claude Fernandez', 'An Implementation of an Efficient Algorithm for Bisimulation Equivalence', '1989-01-01', 'Science of Computer Programming', '13', '', '13--219', '', '', '', '', '', '', '', NULL, '2015-11-24', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(156, 'chaudhuri-plas09', 'Chaudhuri, Avik', '{Language-based security on Android}', '2009-01-01', 'PLAS ''09: Proceedings of the ACM SIGPLAN Fourth Workshop on Programming Languages and Analysis for Security', '', '', '1--7', '', '', 'android, mobile\\_devices, security', '', 'New York, NY, USA', 'ACM', '', NULL, '2015-11-24', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(157, 'felt2011', 'Adrienne P. Felt and\r\nErika Chin and Steve Hanna and Dawn Song and David Wagner', '{Android permissions demystified}', '2011-01-01', ' In Proceedings of the 18th ACM\r\nconference on Computer and communications security', '', '', '627--638', '', '', '', '', '', '', '', NULL, '2015-11-24', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(158, 'Liris-4207', 'Ana {Cavalli} and Azzedine {Benameur} and Wissam\r\n    {Mallouli} and Keqin {Li}', '{A Passive Testing Approach for Security Checking and its\r\n    Practical Usage for Web Services Monitoring}', '2009-01-01', 'NOTERE 2009', '', '', '', '', '', '', '', '', '', '', NULL, '2015-11-24', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(159, 'minisat', 'Niklas Een and Niklas Sï¿½rensson', 'Minisat', '2000-01-01', '', '', '', '', 'http://minisat.se', '', '', '', '', '', '', NULL, '2015-11-24', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(160, 'hampi', 'Kiezun, Adam and Ganesh, Vijay and Guo, Philip J. and Hooimeijer, Pieter and Ernst, Michael D.', 'HAMPI: a solver for string constraints', '2009-01-01', 'ISSTA ''09: Proceedings of the eighteenth international symposium on Software testing and analysis', '', '', '105--116', '', '', '', '', 'New York, NY, USA', 'ACM', '', NULL, '2015-11-24', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(161, 'FTW05', 'L. Frantzen and J. Tretmans and T.A.C. Willemse', '{Test Generation Based on Symbolic Specifications}', '2005-01-01', 'FATES 2004', '', '3395', '1-15', '', '', '', 'Lecture Notes in Computer Science', '', 'Springer', 'J. Grabowski and B. Nielsen', NULL, '2015-11-24', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(162, 'UML', '', 'The Object Management Group (OMG),OMG Unified Modeling Language (OMG UML),\r\nSuperstructure\r\n', '2000-01-01', '', '', '', '', 'http://www.omg.org/spec/UML/2.2/Superstructure/PDF', '', '', '', '', '', '', NULL, '2015-11-24', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(163, 'Mouelhi:2008:MFS:1434657.1434710', 'Mouelhi, Tejeddine and Fleurey, Franck and Baudry, Benoit and Traon, Yves', 'A Model-Based Framework for Security Policy Specification, Deployment and Testing', '2008-01-01', 'Proceedings of the 11th international conference on Model Driven Engineering Languages and Systems', '', '', '537--552', '', '', 'Metamodeling, Model-driven engineering methodology, Security', 'MoDELS ''08', 'Berlin, Heidelberg', 'Springer-Verlag', '', NULL, '2015-11-24', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(164, 'Cohen03constructingtest', 'Myra B. Cohen and Peter B. Gibbons and Warwick B. Mugridge', 'Constructing test suites for interaction testing', '2003-01-01', 'Proc. Intl. Conf. on Software Engineering (ICSE)', '', '', '38--48', '', '', '', '', '', '', '', NULL, '2015-11-24', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(165, 'DeMillo', 'Richard A. DeMillo,Richard J. Lipton,Frederick G. Sayward', 'Hints on Test Data Selection: Help for the Practicing Programmer', '1978-01-01', 'Computer', '11', '4', '34-41', '', '', '', '', 'Long Beach CA 90803', '', '', NULL, '2015-11-24', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(166, 'Martin:2006:ATG:1176617.1176708', 'Martin, Evan', 'Automated test generation for access control policies', '2006-01-01', 'Companion to the 21st ACM SIGPLAN symposium on Object-oriented programming systems, languages, and applications', '', '', '752--753', '', '', 'XACML, access control policy, test generation', 'OOPSLA ''06', 'New York, NY, USA', 'ACM', '', NULL, '2015-11-24', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(167, 'letraon07', 'Le Traon, Yves and Mouelhi, Tejeddine and Baudry, Benoit', 'Testing security policies: going beyond functional testing', '2007-01-01', 'ISSRE''07 (Int. Symposium on Software Reliability Engineering)', '', '', '', '', '', '', '', '', '', '', NULL, '2015-11-24', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(168, 'orbac', 'Kalam, Anas Abou El and Benferhat, Salem and Mi\\`{e}ge, Alexandre and Baida, Rania El and Cuppens, Fr\\''{e}d\\''{e}ric and Saurel, Claire and Balbiani, Philippe and Deswarte, Yves and Trouessin, Gilles', 'Organization based access control', '2003-01-01', 'Proceedings of the 4th IEEE International Workshop on Policies for Distributed Systems and Networks', '', '', '', '', '', '', 'POLICY ''03', '', '', '', NULL, '2015-11-24', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(169, 'Liris-3497', 'Wissam {Mallouli} and Fayï¿½al {Bessayah} and Ana {Cavalli}\r\n    and Azzedine {Benameur}', '{Security Rules Specification and Analysis Based on\r\n    Passive Testing}', '2008-01-01', 'The IEEE Global Communications Conference (GLOBECOM\r\n    2008)', '', '', '', '', '', '', '', '', '', 'IEEE', NULL, '2015-11-24', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(170, 'DGF04', 'Donald G. Firesmith', 'Specifying Reusable Security Requirements', '2004-01-01', 'Journal of Object Technology (JOT)', '', '1', '61-75', '', '', '', '', '', 'Swiss Federal Institute of Technology (ETH), Zurich, Switzerland', 'J. Grabowski and B. Nielsen', NULL, '2015-11-24', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(171, 'ISO2009', '{ISO/IEC}', '{Common Criteria for Information Technology Security (CC)}', '2009-01-01', 'ISO/IEC 15408, version 3.1, ISO/IEC 15408', '', '', '', '', '', '', '', '', '', '', NULL, '2015-11-24', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(172, 'SP10', 'M. Singh and S. Pattterh', 'Formal Specification of Common Criteria Based Access Control Policy', '2010-01-01', 'International Journal of Network Security', '', '', ' 139-148', '', '', '', '', '', '', '', NULL, '2015-11-24', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(173, '796919', 'Kropp,, N. P. and Koopman,, P. J. and Siewiorek,, D. P.', 'Automated Robustness Testing of Off-the-Shelf Software Components', '1998-01-01', 'FTCS ''98: Proceedings of the The Twenty-Eighth Annual International Symposium on Fault-Tolerant Computing', '', '', '230', '', '', '', '', 'Washington, DC, USA', 'IEEE Computer Society', '', NULL, '2015-11-24', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(174, 'owasp', 'OWASP', 'OWASP Testing Guide V3.0 project', '2000-01-01', '', '', '', '', '', '', '', '', '', '', '', NULL, '2015-11-24', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(175, 'SQLInj', 'Neil Daswani and Christoph Kern and Anita Kesavan', 'Foundations of Security', '2007-01-01', '', '', '', '123--138', '', '', '', '', '', ' Apress, Berkely, CA, USA ', '', NULL, '2015-11-24', 5, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(176, 'Mallouli07', 'Wissam Mallouli and Jean-Marie Orset and Ana Cavalli and Nora Cuppens-Boulahia and Fr{\\''e}d{\\''e}ric Cuppens', 'A formal approach for testing security rules', '2007-01-01', '12th ACM symposium on Access control models and technologies, SACMAT', '', '', '127-132', '', '', '', '', '', '', '', NULL, '2015-11-24', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(177, 'nasm05', 'F. Cuppens and  N. Cuppens-Boulahia and T. Sans', 'Nomad : A Security Model with Non Atomic Actions and Deadlines', '2005-01-01', 'Computer Security Foundations. CSFW-18 2005. 18th IEEE Workshop ', '', '', '186--196', '', '', '', '', '', '', '', NULL, '2015-11-24', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(178, 'OME09', 'Ongtang, Machigar and McLaughlin, Stephen and Enck, William and McDaniel, Patrick', 'Semantically Rich Application-Centric Security in Android', '2009-01-01', 'Proceedings of the 2009 Annual Computer Security Applications Conference', '', '', '340--349', '', '', '', 'ACSAC ''09', '', '', '', NULL, '2015-11-24', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(179, 'EAK10', 'Chin, Erika and Felt, Adrienne Porter and Greenwood, Kate and Wagner, David', 'Analyzing inter-application communication in Android', '2011-01-01', 'Proceedings of the 9th international conference on Mobile systems, applications, and services', '', '', '239--252', '', '', '', '', '', '', '', NULL, '2015-11-24', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(180, 'MDJ09', 'Marchand, Herv{\\''e} and Dubreil, J{\\''e}r{\\''e}my and J{\\''e}ron, Thierry', '{Automatic Testing of Access Control for Security Properties}', '2009-01-01', '{TESTCOM/FATES 2009}', '', '', '', '', '', '', '', '', '', '', NULL, '2015-11-24', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(181, 'MFBT12', 'Mouelhi, Tejeddine and Fleurey, Franck and Baudry, Benoit and Traon, Yves', 'A Model-Based Framework for Security Policy Specification, Deployment and Testing', '2008-01-01', 'Proceedings of the 11th international conference on Model Driven Engineering Languages and Systems', '', '', '537--552', '', '', '', '', '', '', '', NULL, '2015-11-24', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(182, 'MMC09', 'Wissam Mallouli and Amel Mammar and Ana Rosa Cavalli', 'A Formal Framework to Integrate Timed Security Rules within\r\na TEFSM-Based System Specification', '2009-01-01', '16th Asia-Pacific Software Engineering Conference\r\n(ASPEC''09), Malaysia', '', '', '', '', '', '', '', '', '', '', NULL, '2015-11-24', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(183, 'Cohen03', 'Cohen, Myra B. and Gibbons, Peter B. and Mugridge, Warwick B. and Colbourn, Charles J.', 'Constructing test suites for interaction testing', '2003-01-01', 'Proc. of the 25th International Conference on Software Engineering', '', '', '38--48', '', '', '', '', '', '', '', NULL, '2015-11-24', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(184, 'Report', 'Report', 'IT Business: Android Security', '2001-01-01', 'http:// www.itbusinessedge.com/cm/blogs/weinschenk/ google-must-deal-with-android-security-problems-quickly/?cs=49291, , last accessed feb 2013', '', '', '', '', '', '', '', '', '', '', NULL, '2015-11-24', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(185, 'M01', 'Peter Muchogou', '{Java Uml reverse Engineer}', '2015-01-01', '{MSc Distributed Multimedia Systems}', '', '', '', '', '', '', '', '', '', '', NULL, '2015-11-24', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(186, 'EAKD11', 'Chin, Erika and Felt, Adrienne Porter and Greenwood, Kate and Wagner, David', 'Analyzing inter-application communication in Android', '2011-01-01', 'Proc. of the 9th International Conference on Mobile Systems, Applications, and Services', '', '', '', '', '', '', '', '', '', '', NULL, '2015-11-24', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(187, 'AHKSD12', 'Marback, Aaron and Do, Hyunsook and\r\nHe, Ke and Kondamarri, Samuel and Xu, Dianxiang', 'A\r\nthreat model-based approach to security testing', '2013-01-01', 'Software: Practice and Experience', '43', '2', '241--258', '', '', 'threat\r\nmodeling, threat trees, security testing, software testing', '', '', '', '', NULL, '2015-11-24', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(188, 'EG10', 'Enck, William and Gilbert, Peter and Chun, Byung-Gon and Cox, Landon P. and Jung, Jaeyeon and McDaniel, Patrick and Sheth, Anmol N.', 'TaintDroid: an information-flow tracking system for realtime privacy monitoring on smartphones', '2010-01-01', 'Proc. of the 9th USENIX conference on Operating systems design and implementation', '', '', '', '', '', '', '', '', '', '', NULL, '2015-11-24', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(189, 'Benli', 'Benli, Selin and Habash, Anthony and Herrmann, Andy and Loftis, Tyler and Simmonds, Devon', 'A Comparative Evaluation of Unit Testing Techniques on a Mobile Platform', '2012-01-01', 'Proceedings of the 9th International Conference on Information Technology - New Generations', '', '', '263--268', '', '', 'Software Engineering, Unit Testing, Android Applications, White Box Testing, Black Box Testing', 'ITNG ''12', '', 'IEEE Computer Society', '', NULL, '2015-11-24', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(190, 'jing', 'Jing, Yiming and Ahn, Gail-Joon and Hu, Hongxin', 'Model-Based Conformance Testing for Android.', '2001-01-01', 'Proceedings of the 7th International Workshop on Security (IWSEC)', '63', '', '1-18', '', '', 'dblp', 'Lecture Notes in Computer Science', '', 'Springer', 'Hanaoka, Goichiro and Yamauchi, Toshihiro', NULL, '2015-11-24', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(191, 'zhong', 'Jiagui Zhong and Jianjun Huang and Bin Liang', 'Android Permission Re-delegation Detection and Test Case Generation', '2012-01-01', 'Computer Science Service System (CSSS), 2012 International Conference on', '', '', '871 -874', '', '', '', '', '', '', '', NULL, '2015-11-24', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(192, 'grace', 'Grace, Michael and Zhou, Yajin and Wang, Zhi and Jiang, Xuxian', 'Systematic Detection of Capability Leaks in Stock {Android} Smartphones', '2012-01-01', 'Proceedings of the 19th Network and Distributed System Security Symposium (NDSS)', '', '', '', '', '', '', '', '', '', '', NULL, '2015-11-24', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(193, 'Azim13', 'Azim, Tanzirul and Neamtiu, Iulian', 'Targeted and Depth-first Exploration for Systematic Testing of Android Apps', '2013-01-01', 'Proceedings of the 2013 ACM SIGPLAN International Conference on Object Oriented Programming Systems Languages \\&\\#38; Applications', '', '', '641--660', '', '', 'code coverage, dynamic analysis, google android, greybox testing, gui testing, systematic exploration, taint analysis, test case generation', 'OOPSLA ''13', 'New York, NY, USA', 'ACM', '', NULL, '2015-11-24', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(194, 'az8585', 'Momo de la Courneuve', 'PubliAllChamps', '2015-11-03', 'fff', 'ded', '47', '47', 'yhyet', 'dedde', 'jtyjyu, hytju, lol', 'rff', 'Miami, USA', 'Flammarion', 'Flammarion', 'useruploads/files/AffichageResultats.pdf', '22 may 2015', 2, 'doi', 'http://google.fr', 'instest', 'how', 'dateurl', '1FR007ASSE42', '5'),
(196, '"rf', 'f(''', 'Test3', '2015-11-04', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 3, NULL, NULL, 'insticouillon', NULL, NULL, NULL, NULL);

--
-- Contraintes pour les tables exportées
--

--
-- Contraintes pour la table `publication`
--
ALTER TABLE `publication`
  ADD CONSTRAINT `publication_ibfk_1` FOREIGN KEY (`categorie_id`) REFERENCES `categorie` (`ID`);

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
