<?php

    //Importation script CKEditor   
    echo $this->headScript()->prependFile($this->basePath('js/ckeditor/ckeditor.js'));
    echo $this->headScript()->prependFile($this->basePath('js/ckfinder/ckfinder.js'));

    $this->headTitle('Cr√©ation Rubrique');
    
    if($langue == 'fr') {
        echo "<p class='info_form'><img src=".$this->basePath().'/img/icon_information.png'." alt='Information' width=20 height=20 />Les champs pr√©c√©d√©s du signe * sont obligatoires.</p>";
    }
    elseif($langue == 'en') {
        echo "<p class='info_form'><img src=".$this->basePath().'/img/icon_information.png'." alt='Information' width=20 height=20 />Fields preceded of the * symbol are mandatory.</p>";
    }
    
    /*if(isset($exception) || isset($errorFiltre)) {
        if($langue == 'fr') {
            echo "<b class='erreur_form'><img src=".$this->basePath().'/img/icon_error.png'." alt='Error' width=20 height=20 />Erreur lors de la crÈation de la rubrique. Veuillez rÈessayer.</b> <br />";
            echo "<i class='erreur_form'>Rappel: La position doit Ítre supÈrieure ‡ 0.</i>";
        }
        elseif($langue == 'en') {
            echo "<b class='erreur_form'><img src=".$this->basePath().'/img/icon_error.png'." alt='Error' width=20 height=20 />Error during rubric creation. Please retry.</b> <br />";
            echo "<i class='erreur_form'>Reminder: The position must be greater than 0.</i>";
        }
    }*/
    
    $form->setAttribute('action', $this->url('createrubrique', array('action' => 'createRubrique', 'langue' => $langue)));
    $form->prepare();
    
    echo $this->form()->openTag($form);
    
    //CrÈation du formulaire
    $titreFr = $form->get('titre_fr');
    $titreEn = $form->get('titre_en');
    $actifRadio = $form->get('actifradio');
    $position = $form->get('position');
    $textareaFr = $form->get('content_fr');
    $textareaEn = $form->get('content_en');
    $bouton = $form->get('submit');
    
    if($langue == 'en') {
        $titreFr->setLabel('French title*');
        $titreEn->setLabel('English title*');
        $actifRadio->setLabel('Visible on the website ?*');
        $position->setLabel('Position*');
        $textareaFr->setLabel('French content*');
        $textareaEn->setLabel('English content*');
        $bouton->setValue('Submit');
    }
    
    echo $this->formRow($titreFr)."<br /> <br />";
    echo $this->formRow($titreEn)."<br /> <br />";
    echo $this->formRow($actifRadio)."<br /> <br />";
    echo $this->formRow($position)."<br /> <br />";
    echo $this->formRow($textareaFr)."<br /> <br />";
    echo $this->formRow($textareaEn)."<br /> <br />";
    echo $this->formSubmit($bouton);
    
    echo $this->form()->closeTag();

?>    
    
<script type="text/javascript">

    CKEDITOR.replace('editor_fr' ,
    {
        filebrowserBrowseUrl : '/ckfinder/ckfinder.html',
        filebrowserImageBrowseUrl : '/ckfinder/ckfinder.html?Type=Images',
        filebrowserFlashBrowseUrl : '/ckfinder/ckfinder.html?Type=Flash',
        filebrowserUploadUrl : '/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Files',
        filebrowserImageUploadUrl : '/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Images',
        filebrowserFlashUploadUrl : '/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Flash'
    });
    CKEDITOR.replace('editor_en' ,
    {
        filebrowserBrowseUrl : '/ckfinder/ckfinder.html',
        filebrowserImageBrowseUrl : '/ckfinder/ckfinder.html?Type=Images',
        filebrowserFlashBrowseUrl : '/ckfinder/ckfinder.html?Type=Flash',
        filebrowserUploadUrl : '/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Files',
        filebrowserImageUploadUrl : '/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Images',
        filebrowserFlashUploadUrl : '/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Flash'
    });

</script>