<html lang="fr">
	<head>
		<meta charset="utf-8"/>
		<meta name="viewport" content="width=device-width, initial-scale=1">
		
		<title>Titre</title>
	   
		<link rel="stylesheet" type="text/css" media="all" href="public/css/styles.css">
			  <script type="text/javascript" src="public/js/jquery-1.10.2.min.js"></script>

		  <script type="text/javascript" src="public/js/publication-index.js"></script>

		<link rel="stylesheet" href="../../../../public/css/pop-up.css">
	</head>
	<body>

		<div class="wrap">
			<img src="../../img/logo.png" alt="logo" style="width:20%; margin-left:-20%;padding-bottom:30px;margin-top:20px;">
			<div id="language">
				<a href="?r=site/index&locale=fr"><img src="../../img/flag-fr.png" /></a> 
				<a href="?r=site/index&locale=en"><img src="../../img/flag-en.png" /></a>
			</div>
			
			<div class="container">
				
			</div>
		</div>
	</br></br>
		<footer class="footer">
			<div class="container">
				<p class="pull-left">&copy; My Company <?= date('Y') ?></p>
				<p class="pull-right"></p>
			</div>
		</footer>


	</body>
</html>


  <script type="text/javascript" src="public/js/jquery.tablesorter.js"></script>  
  <script type="text/javascript" src="public/js/effet.js"></script>
