<!DOCTYPE html>

<html lang="fr">
	<head>
		<meta charset="utf-8"/>
		<meta name="viewport" content="width=device-width, initial-scale=1"/>
		
		<title>NOM PERSONNE</title>
		<?php 
		echo $this->headLink()->prependStylesheet($this->basePath().'css/site.css');
		echo $this->headLink()->prependStylesheet($this->basePath().'css/styles.css');
		echo $this->headLink()->prependStylesheet($this->basePath().'css/pop-up.css');
	?>
	
	</head>
	<body>
		<div class="site-content">
			<div class="logo"></div>
			<div class="icons-contener">
					<div class="icon"><a href="?r=site/index&locale=fr"><img src="../../img/flag-fr.png" /></a></div>
					<div class="icon"><a href="?r=site/index&locale=en"><img src="../../img/flag-en.png" /></a></div>
			</div>
			
			<div class="menu-container">
				<div class="menu-corner-right"></div>
				<div class="menu-corner-left"></div>
				<div class="menu-button-list">
					<?php
					/// appelle de service pour affichage des rubrique
					//<div class="menu-item">NOM</div>
					//<div class="menu-separator"></div> ....
					?>
				</div>				
			</div>
			<div class="text-contener">
				<div class="text-content" style="position: relative; overflow: hidden;">
			
					<?php
						///// content
					?>
			    </div>
			</div>	
			
			
			<div>	
				<div class="footer-corner-left"></div>
				<div class="footer-middle"></div>
				<div class="footer-corner-right"></div>
			</div>	
		</div>
	</body>
</html>


 
