<?php echo $this->doctype(); ?>
 
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>
 
        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>
		
		<?php 
		//$serviceLocator = $this->getServiceLocator();
		//$config = $serviceLocator->get('config');
		//$langue = $config['langue'];
		?>
        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() .'/css/style.css')
                        ->prependStylesheet($this->basePath() .'/css/bootstrap.min.css') 
						->prependStylesheet($this->basePath() .'/css/site.css')
						->prependStylesheet($this->basePath() .'/css/pop-up.css');?>
 
        <!-- Scripts -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                      ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                                      ->prependFile($this->basePath() . '/js/jquery.min.js') ?>
 
    </head>
    <body>
        		<div class="site-content">
			<div class="logo"></div>
			<div class="icons-contener">
					<div class="icon"><a href="?r=site/index&locale=fr"><img src="../../img/flag-fr.png" /></a></div>
					<div class="icon"><a href="?r=site/index&locale=en"><img src="../../img/flag-en.png" /></a></div>
			</div>
			
				<div class="menu-corner-left"></div>
				<div class="menu-container">	
					<div class="menu-button-list">
						<?php
						/// appelle de service pour affichage des rubrique a partir du controller
						/// verification langue
						
						foreach($this->listeRubrique as $item)
						{
							echo "<div class='menu-item'><a href=".$this->url('laRubrique',array('id_menu' => $item['menu_id'])).">";
							
							//if($langue='fr'){
								echo $item['titre_fr'];
							/*else{ 
								echo $item['titre_en'];}							
							*/
							echo " </a></div>
							<div class='menu-separator'></div>";
						}
						
						echo "<div class='menu-item'><a href='".$this->url('publications')."'>Publications</a></div>";?>
						
					</div>									
				</div>
				<div class="menu-corner-right"></div>
				
			<div class="text-contener">
				<div class="text-content" style="position: relative; overflow: hidden;">
			
					<?php
						echo $this->content;
					?>
			    </div>
			</div>	
			
			
			<div class="cont">
			<div class="footer-corner-left"></div><div class="footer-middle"></div><div class="footer-corner-right"></div>
			</div>	
		</div>               
        <?php echo $this->inlineScript() ?>
    </body>
</html>