<?php echo "<table cellspacing='0' cellpadding='0'>
	<tbody>
		<tr>
			<td height='40px' align='left' style='vertical-align:top;'>
				<table class='publication-filter-panel' cellpadding='0' cellspacing='0'>
					<tbody>
						<tr>
							<td width='50%' align='center' style='vertical-align:top;'>
								<div class='ibtn' style='position: relative, overflow: hidden;'>
									<img class='float-left' src=''/>
									<div class='ibtn-lbl'>Trier par catégorie</div>
								</div>
							</td>
							<td width='50%' align='center' style='vertical-align:top;'>
								<div class='ibtn' style='position: relative, overflow: hidden;'>
									<img class='float-left' src=''/>
									<div class='ibtn-lbl'>Trier par date</div>
								</div>
							</td>
						</tr>
					</tbody>
				</table>
			</td>
		</tr>
		<tr>
			<td align='left' style='vertical-align:top;'>
				<div class='publication-contener' style='position: relative; overflow: hidden;'>
				";
					
				//debut tableau par CATEGORIE
				foreach($listeCateg as $categ){
				echo "
					<table cellspacing='0' cellpadding='0' style='width:100%'>
						<tbody>
							<tr>
								<td align='left' style='vertical-align:top;'>
									<div class='publications-section-title'>";
										if($langue=='fr'){echo $categ['name_en'];}
										else{echo $categ['name_en'];}
									echo "</div>
								</td>
							</tr>
							<td align='left' style='vertical-align:top;'>
								<table class='publication-items' cellspacing='0' cellpadding='0' style='width:100%;'>
									<tbody>";
										//debut tableau PUBLICATION
										foreach($listePubli as $item){
										if($item['categorie_id']==$categ['ID']){
										echo "<tr>
											<td align='left' style='vertical-align: top;'>
												<table class='publications-item' cellpadding='0' cellspacing='0'>
													<tbody>
														<tr>
															<td align='left' style='vertical-align:top;'>
																<div class='gwt-HTML' style='white-space:normal';>
																	<div>";
																									
																		echo "<span class='publi-ref'>[".$item['ID']."] </span>";
																		echo "<span class='publi-authors'>".$item['auteurs'].", </span>";
																		echo "<span class='publi-titre'>".$item['titre'].", </span>";
																		echo "<span class='publi-booktitle'>".$item['journal']."</span>";
																		echo "<span class='publi-volume'>".$item['volume']."</span>";
																		echo "<span class='publi-number'>".$item['number']."</span>";
																		echo "<span class='publi-pages>".$item['pages']."</span>";
																		echo "<span class='publi-publisher'>".$item['publisher']."</span>";
																		echo "<span class='publi-date'>".$item['date']."</span>";
																		echo "<span class='publi-abstract'>".$item['abstract']."</span>";
																		echo "<span class='publi-keywords'>".$item['keywords']."</span>";
																	
																	echo "</div>
																</div>
															</td>
														</tr>
														<tr>
															<td align='left' style='vertical-align: top;'>
																<table cellpadding='0' cellspacing='0'>
																	<tbody>
																		<tr>
																			<td align='left' style='vertical-align:top;'><img class='cursor-pointer' src='".$this->basePath().'/img/icon-pdf.png'."'/></td>
																				<td align='left' style='vertical-align:top;'><img class='cursor-pointer' src='".$this->basePath().'/img/icon-tex.png'."'/></td>
																		</tr>
																	</tbody>
																</table>
															</td>
														</tr>
													</tbody>
												</table>
											</td>
										</tr>";}}
									echo "</tbody>
								</table>
							</td>									
						</tbody>
					</table>";}
				//fin du tableau 
				echo "</div>
			</td>
		</tr>							
	</tbody>	
</table>";
 ?>