<script type="text/javascript">
        $(function() {
            $( "#datepicker1" ).datepicker({
                dateFormat: "yy-mm-dd"
            });
            $( "#datepicker2" ).datepicker({
                dateFormat: "yy-mm-dd"
            });
            $( "#accordion" ).accordion({
                'animate': {duration: 600, easing: 'swing'}
            });
        });
        
        $(document).ready(function() {
            choixCategorie($("#categorie").val());
            $("#oblige > div > label").each(function() {
                $(this).text($(this).text() + '*');
            });
            $("#oblige > div").each(function() {
                if($(this).css('display') === 'block') {
                    $(this).find('input').prop('required', true);
                }
                else {
                    $(this).find('input').prop('required', false);
                }
            });
            $("#categorie").change(function() {
                choixCategorie($(this).val());
                $("#oblige > div").each(function() {
                    if($(this).css('display') === 'block') {
                        $(this).find('input').prop('required', true);
                    }
                    else {
                        $(this).find('input').prop('required', false);
                    }
                });
            });
        });
        
</script>

<?php

    //Importation script CKEditor   
    echo $this->headScript()->prependFile($this->basePath('js/ckeditor/ckeditor.js'));
    //Importation jquery-ui pour DatePicker eg l'accordÈon
    echo $this->headScript()->prependFile($this->basePath('js/jquery-ui-1.11.4.custom/jquery-ui.js'));
    echo $this->headLink()->prependStylesheet($this->basePath('js/jquery-ui-1.11.4.custom/jquery-ui.css'));
    //GÈnÈrer le formulaire selon la catÈgorie choisie
    echo $this->headScript()->prependFile($this->basePath('js/form_categ.js'));
    
    
    if($langue != 'fr' && $langue != 'en') {
        echo "<h2>La langue doit etre <b>fr</b> ou <b>en</b>.</h2>";
    }
    else {
    
        if($langue == 'fr') {
            echo "<p class='info_form'><img src=".$this->basePath().'/img/icon_information.png'." alt='Information' width=20 height=20 />Les champs pr√©c√©d√©s du signe * sont obligatoires.</p>";
        }
        elseif($langue == 'en') {
            echo "<p class='info_form'><img src=".$this->basePath().'/img/icon_information.png'." alt='Information' width=20 height=20 />Fields preceded of the * symbol are mandatory.</p>";
        }

        if(isset($exCreatePublication)) {
            if($langue == 'fr') {
                echo "<p class='erreur_form'><img src=".$this->basePath().'/img/icon_error.png'." alt='Error' width=20 height=20 />Erreur lors de la cr√©ation de la publication. Veuillez r√©essayer.</p>";
            }
            elseif($langue == 'en') {
                echo "<p class='erreur_form'><img src=".$this->basePath().'/img/icon_error.png'." alt='Error' width=20 height=20 />Error during publication creation. Please retry</p>";
            }
        }
        if(isset($errorMsgExtension)) {
            if($langue == 'fr') {
                echo "<p class='erreur_form'><img src=".$this->basePath().'/img/icon_error.png'." alt='Error' width=20 height=20 />".$errorMsgExtension."</p>";
            }
            elseif($langue == 'en') {
                echo "<p class='erreur_form'><img src=".$this->basePath().'/img/icon_error.png'." alt='Error' width=20 height=20 />The extension file must be pdf.</p>";
            }
        }

        $form->setAttribute('action', $this->url('createpublication', array('action' => 'createPublication', 'langue' => $langue)));
        $form->prepare();

        //CrÈation du formulaire
        $titre = $form->get('titre');
        $reference = $form->get('reference');
        $auteurs = $form->get('auteurs');
        $date = $form->get('date');
        $journal = $form->get('journal');
        $abstract = $form->get('abstract');
        $volume = $form->get('volume');
        $nb = $form->get('number');
        $pages = $form->get('pages');
        $note = $form->get('note');
        $keywords = $form->get('keywords');
        $series = $form->get('series');
        $localite = $form->get('localite');
        $publisher = $form->get('publisher');
        $editor = $form->get('editor');
        $pdf = $form->get('pdf');
        $categorie= $form->get('categorie_id');
        $dateDisplay = $form->get('date_display');
        $doi = $form->get('doi');
        $url = $form->get('url');
        $institution = $form->get('institution');
        $howpublished = $form->get('howpublished');
        $urldate = $form->get('urldate');
        $isbn = $form->get('isbn');
        $chapter = $form->get('chapter');
        $booktitle = $form->get('booktitle');
        $type = $form->get('type');
        $bouton = $form->get('submit');

        if($langue == 'en') {
            $titre->setLabel('Title');
            $reference->setLabel('Reference');
            $auteurs->setLabel('Author(s)');
            $date->setLabel('Date');
            $journal->setLabel('Journal');
            $abstract->setLabel('Abstract');
            $volume->setLabel('Voulme');
            $nb->setLabel('Number');
            $pages->setLabel('Page number');
            $note->setLabel('Note');
            $keywords->setLabel('Keywords');
            $series->setLabel('Series');
            $localite->setLabel('Localite');
            $publisher->setLabel('Publisher');
            $editor->setLabel('Editor');
            $pdf->setLabel('Upload PDF file');
            $dateDisplay->setLabel('Date to display');
            $categorie->setLabel('Category');
            $booktitle->setLabel('Book title');
            $bouton->setValue('Submit');
        }

        echo $this->form()->openTag($form);

        echo "<div id='accordion' style='margin-top:25px'>";

        echo "<h3>Champs obligatoires</h3>";
        echo "<div id='oblige'>";
            echo "<div id='titre_bloc'>".$this->formRow($titre)."</div>";
            echo "<div id='reference_bloc'>".$this->formRow($reference)."</div>";
            echo "<div id='auteurs_bloc'>".$this->formRow($auteurs)."</div>";
            if($listeCategories != null) {
                $catList = array();
                foreach($listeCategories as $cat) {
                    if($langue == 'fr') {
                        $catList[$cat['ID']] = $cat['name_fr'];
                    }
                    else if($langue = 'en') {
                        $catList[$cat['ID']] = $cat['name_en'];
                    }
                }
                $categorie->setValueOptions($catList);
                echo "<div id='categorie_bloc'>".$this->formRow($categorie)."</div>";
            }
            echo "<div id='date_bloc'>".$this->formRow($date)."</div>";
            echo "<div id='journal_bloc'>".$this->formRow($journal)."</div>";
            echo "<div id='editor_bloc'>".$this->formRow($editor)."</div>";
            echo "<div id='type_bloc'>".$this->formRow($type)."</div>";
            echo "<div id='institution_bloc'>".$this->formRow($institution)."</div>";
            echo "<div id='booktitle_bloc'>".$this->formRow($booktitle)."</div>";
        echo "</div>"; //fin div deroulante 'Champs communs obligatoires'

        echo "<h3>Champs optionnels</h3>";
        echo "<div id='opt'>";
            echo "<div id='series_bloc'>".$this->formRow($series)."</div>";
            echo "<div id='localite_bloc'>".$this->formRow($localite)."</div>";
            echo "<div id='publisher_bloc'>".$this->formRow($publisher)."</div>";
            echo "<div id='doi_bloc'>".$this->formRow($doi)."</div>";
            echo "<div id='url_bloc'>".$this->formRow($url)."</div>";
            echo "<div id='datedisplay_bloc'>".$this->formRow($dateDisplay)."</div>";
            echo "<div id='howpublished_bloc'>".$this->formRow($howpublished)."</div>";
            echo "<div id='urldate_bloc'>".$this->formRow($urldate)."</div>";
            echo "<div id='volume_bloc'>".$this->formRow($volume)."</div>";
            echo "<div id='nb_bloc'>".$this->formRow($nb)."</div>";
            echo "<div id='pages_bloc'>".$this->formRow($pages)."</div>";
            echo "<div id='isbn_bloc'>".$this->formRow($isbn)."</div>";
            echo "<div id='chapter_bloc'>".$this->formRow($chapter)."</div>";
            echo "<div id='keywords_bloc'>".$this->formRow($keywords)."</div>";
        echo "</div>"; //fin div deroulante 'Champs optionnels'

         echo "<h3>Note & abstract</h3>";
        echo "<div>";
            echo "<div id='note_bloc'>".$this->formRow($note)."</div>";
            echo "<div id='abstract_bloc'>".$this->formRow($abstract)."</div>";
        echo "</div>"; //fin div deroulante 'Note & abstract'

        echo "<h3>Importer fichier PDF</h3>";
        echo "<div>";
            echo "<div id='pdf_bloc'>".$this->formRow($pdf)."</div>";
        echo "</div>"; //fin div deroulante 'Importer fichier PDF'
        echo "</div>"; //fin div avec id=accordion

        echo $this->formSubmit($bouton);

        echo $this->form()->closeTag();
    }
